// Lesson 8 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/.../lektion7.js - see main.js's
// INTERACTIVE_LESSONS map, which intercepts the "deutsch-almani-lektion-8"
// course card (a plain courses-table row, just for the level/title/grid-
// card metadata) and renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion8 = {
  id: 'lektion8',
  courseId: 'deutsch-almani-lektion-8',
  title: "Lektion 8 – Trennbare Verben, Bewegung, Um ... zu und Dass",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-8-v1',
  promptLang: 'en',
  // Formal register throughout (Sie/Ihnen).
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"weg","persian":"away"}],"promptFa":"I am going away.","expectedAnswer":"Ich gehe weg."},
    {"id":2,"software":[{"german":"weggehen","persian":"to go away"}],"promptFa":"I will go away soon.","expectedAnswer":"Ich werde bald weggehen."},
    {"id":3,"software":[],"promptFa":"I would not go away without you.","expectedAnswer":"Ich würde ohne Sie nicht weggehen."},
    {"id":4,"software":[{"german":"wegfahren","persian":"to drive / travel away"}],"promptFa":"I am leaving by car.","expectedAnswer":"Ich fahre weg."},
    {"id":5,"software":[],"promptFa":"We will leave tomorrow.","expectedAnswer":"Wir werden morgen wegfahren."},
    {"id":6,"software":[{"german":"aus","persian":"out"},{"german":"ausgehen","persian":"to go out"}],"promptFa":"I am going out this evening.","expectedAnswer":"Ich gehe heute Abend aus."},
    {"id":7,"software":[{"german":"möchten","persian":"would like, plural/formal"}],"promptFa":"We would like to go out this evening.","expectedAnswer":"Wir möchten heute Abend ausgehen."},
    {"id":8,"software":[],"promptFa":"Would you like to go out this evening?","expectedAnswer":"Möchten Sie heute Abend ausgehen?"},
    {"id":9,"software":[{"german":"Ausgang","persian":"exit"},{"german":"Ausfahrt","persian":"exit for vehicles"},{"german":"Eingang","persian":"entrance"},{"german":"Einfahrt","persian":"entrance for vehicles"}],"promptFa":null,"expectedAnswer":null},
    {"id":10,"software":[{"german":"abfahren","persian":"to depart"}],"promptFa":"We will depart tomorrow.","expectedAnswer":"Wir werden morgen abfahren."},
    {"id":11,"software":[],"promptFa":"When will you depart?","expectedAnswer":"Wann werden Sie abfahren?"},
    {"id":12,"software":[{"german":"durchfahren","persian":"to drive through"}],"promptFa":"We are driving through.","expectedAnswer":"Wir fahren durch."},
    {"id":13,"software":[{"german":"durchgehen","persian":"to walk through / go through"}],"promptFa":"We are going through.","expectedAnswer":"Wir gehen durch."},
    {"id":14,"software":[{"german":"wieder","persian":"again"}],"promptFa":"I will do it again.","expectedAnswer":"Ich werde es wieder tun."},
    {"id":15,"software":[],"promptFa":"I will call you again later.","expectedAnswer":"Ich werde Sie später wieder anrufen."},
    {"id":16,"software":[{"german":"nie","persian":"never"}],"promptFa":"I will never do it again.","expectedAnswer":"Ich werde es nie wieder tun."},
    {"id":17,"software":[],"promptFa":"I will never go there again.","expectedAnswer":"Ich werde nie wieder dorthin gehen."},
    {"id":18,"software":[{"german":"holen","persian":"to fetch / get"}],"promptFa":"I will get it.","expectedAnswer":"Ich werde es holen."},
    {"id":19,"software":[],"promptFa":"Can you get it for me?","expectedAnswer":"Können Sie es für mich holen?"},
    {"id":20,"software":[{"german":"abholen","persian":"to pick up"}],"promptFa":"I will pick it up.","expectedAnswer":"Ich werde es abholen."},
    {"id":21,"software":[],"promptFa":"I will pick you up.","expectedAnswer":"Ich werde Sie abholen."},
    {"id":22,"software":[],"promptFa":"I will pick you up tomorrow.","expectedAnswer":"Ich werde Sie morgen abholen."},
    {"id":23,"software":[],"promptFa":"Can you pick me up tomorrow?","expectedAnswer":"Können Sie mich morgen abholen?"},
    {"id":24,"software":[{"german":"hole","persian":"I fetch / get"},{"german":"ab","persian":"off / away, separable prefix"}],"promptFa":"I am picking it up.","expectedAnswer":"Ich hole es ab."},
    {"id":25,"software":[{"german":"wiederholen","persian":"to repeat"}],"promptFa":"I repeat it.","expectedAnswer":"Ich wiederhole es."},
    {"id":26,"software":[{"german":"wiederhole","persian":"I repeat"}],"promptFa":"I will repeat it.","expectedAnswer":"Ich werde es wiederholen."},
    {"id":27,"software":[],"promptFa":"Can you repeat it?","expectedAnswer":"Können Sie es wiederholen?"},
    {"id":28,"software":[],"promptFa":"Please repeat it.","expectedAnswer":"Wiederholen Sie es bitte."},
    {"id":29,"software":[{"german":"bekommen","persian":"to receive / get"}],"promptFa":"I receive it.","expectedAnswer":"Ich bekomme es."},
    {"id":30,"software":[{"german":"bekomme","persian":"I receive / get"}],"promptFa":"I will get it tomorrow.","expectedAnswer":"Ich werde es morgen bekommen."},
    {"id":31,"software":[],"promptFa":"When will I get it?","expectedAnswer":"Wann werde ich es bekommen?"},
    {"id":32,"software":[{"german":"an","persian":"on / at; separable prefix"}],"promptFa":"I arrive tomorrow.","expectedAnswer":"Ich komme morgen an."},
    {"id":33,"software":[{"german":"früh","persian":"early"}],"promptFa":"I will arrive early tomorrow.","expectedAnswer":"Ich werde morgen früh ankommen."},
    {"id":34,"software":[],"promptFa":"Can you come early tomorrow?","expectedAnswer":"Können Sie morgen früh kommen?"},
    {"id":35,"software":[{"german":"Mittag","persian":"noon"},{"german":"Nachmittag","persian":"afternoon"}],"promptFa":"I will come this afternoon.","expectedAnswer":"Ich werde heute Nachmittag kommen."},
    {"id":36,"software":[{"german":"Frankfurt","persian":"Frankfurt"}],"promptFa":"We are going to Frankfurt.","expectedAnswer":"Wir fahren nach Frankfurt."},
    {"id":37,"software":[],"promptFa":"We will go to Frankfurt tomorrow.","expectedAnswer":"Wir werden morgen nach Frankfurt fahren."},
    {"id":38,"software":[{"german":"vor","persian":"before / in front of"},{"german":"Vormittag","persian":"morning / before noon"}],"promptFa":"I will come tomorrow morning.","expectedAnswer":"Ich werde morgen Vormittag kommen."},
    {"id":39,"software":[{"german":"übermorgen","persian":"the day after tomorrow"}],"promptFa":"I will go there the day after tomorrow.","expectedAnswer":"Ich werde übermorgen dorthin gehen."},
    {"id":40,"software":[],"promptFa":"We will go to Frankfurt the day after tomorrow.","expectedAnswer":"Wir werden übermorgen nach Frankfurt fahren."},
    {"id":41,"software":[{"german":"hin","persian":"toward there"}],"promptFa":"I am going there.","expectedAnswer":"Ich gehe hin."},
    {"id":42,"software":[],"promptFa":"I am driving there.","expectedAnswer":"Ich fahre hin."},
    {"id":43,"software":[{"german":"herein","persian":"in / inside toward the speaker"},{"german":"hereinkommen","persian":"to come in"}],"promptFa":"Would you like to come in?","expectedAnswer":"Wollen Sie hereinkommen?"},
    {"id":44,"software":[],"promptFa":"Please come in.","expectedAnswer":"Kommen Sie bitte herein."},
    {"id":45,"software":[{"german":"heraus","persian":"out / outward"},{"german":"raus","persian":"out"}],"promptFa":"Go out!","expectedAnswer":"Gehen Sie raus!"},
    {"id":46,"software":[],"promptFa":"Please come in.","expectedAnswer":"Kommen Sie herein, bitte."},
    {"id":47,"software":[{"german":"legen","persian":"to put / lay something horizontally"}],"promptFa":"I put it here.","expectedAnswer":"Ich lege es hier."},
    {"id":48,"software":[{"german":"liegen","persian":"to lie / be lying"}],"promptFa":"It is lying here.","expectedAnswer":"Es liegt hier."},
    {"id":49,"software":[{"german":"stellen","persian":"to put / place something upright"}],"promptFa":"I put it here.","expectedAnswer":"Ich stelle es hier."},
    {"id":50,"software":[{"german":"anlegen","persian":"to put on / place against"}],"promptFa":"I will put it on.","expectedAnswer":"Ich werde es anlegen."},
    {"id":51,"software":[{"german":"einlegen","persian":"to insert / put inside"}],"promptFa":"I will put it inside.","expectedAnswer":"Ich werde es einlegen."},
    {"id":52,"software":[{"german":"lege","persian":"I put / lay"},{"german":"über","persian":"over / above"}],"promptFa":"I put it over there.","expectedAnswer":"Ich lege es dort hin."},
    {"id":53,"software":[{"german":"überlegen","persian":"to think about / consider"}],"promptFa":"I will think about it.","expectedAnswer":"Ich werde es überlegen."},
    {"id":54,"software":[],"promptFa":"I have to think about it.","expectedAnswer":"Ich muss es überlegen."},
    {"id":55,"software":[],"promptFa":"I will think about it and tell you later.","expectedAnswer":"Ich werde es überlegen und es Ihnen später sagen."},
    {"id":56,"software":[{"german":"unterkommen","persian":"to find accommodation / get somewhere"}],"promptFa":"We will find somewhere to stay.","expectedAnswer":"Wir werden unterkommen."},
    {"id":57,"software":[{"german":"runter","persian":"down"}],"promptFa":"Come down!","expectedAnswer":"Kommen Sie runter!"},
    {"id":58,"software":[],"promptFa":"Please come down.","expectedAnswer":"Kommen Sie bitte runter."},
    {"id":59,"software":[{"german":"ziehen","persian":"to pull"}],"promptFa":"I pull it.","expectedAnswer":"Ich ziehe es."},
    {"id":60,"software":[{"german":"Zug","persian":"train"}],"promptFa":"The train will arrive tomorrow morning.","expectedAnswer":"Der Zug wird morgen früh ankommen."},
    {"id":61,"software":[{"german":"anziehen","persian":"to put on clothes / get dressed"}],"promptFa":"I will get dressed.","expectedAnswer":"Ich werde mich anziehen."},
    {"id":62,"software":[{"german":"Anzug","persian":"suit"}],"promptFa":"I will put on the suit.","expectedAnswer":"Ich werde den Anzug anziehen."},
    {"id":63,"software":[{"german":"ziehe","persian":"I pull / I put on"}],"promptFa":"I am getting dressed.","expectedAnswer":"Ich ziehe mich an."},
    {"id":64,"software":[{"german":"zieht","persian":"pulls / puts on"}],"promptFa":"He is getting dressed.","expectedAnswer":"Er zieht sich an."},
    {"id":65,"software":[],"promptFa":"I have to get dressed.","expectedAnswer":"Ich muss mich anziehen."},
    {"id":66,"software":[{"german":"ausziehen","persian":"to move out / take off clothes"}],"promptFa":"I will move out.","expectedAnswer":"Ich werde ausziehen."},
    {"id":67,"software":[{"german":"Auszug","persian":"moving out / departure"},{"german":"Einzug","persian":"moving in"}],"promptFa":null,"expectedAnswer":null},
    {"id":68,"software":[{"german":"umziehen","persian":"to move house / change clothes"}],"promptFa":"I will move.","expectedAnswer":"Ich werde umziehen."},
    {"id":69,"software":[],"promptFa":"We will move soon.","expectedAnswer":"Wir werden bald umziehen."},
    {"id":70,"software":[{"german":"Schlüssel","persian":"key"}],"promptFa":"I have the key.","expectedAnswer":"Ich habe den Schlüssel."},
    {"id":71,"software":[{"german":"dem","persian":"the, dative masculine/neuter"}],"promptFa":"I close it with the key.","expectedAnswer":"Ich schließe es mit dem Schlüssel."},
    {"id":72,"software":[{"german":"schließen","persian":"to close"}],"promptFa":"I close the door.","expectedAnswer":"Ich schließe die Tür."},
    {"id":73,"software":[{"german":"Tür","persian":"door"}],"promptFa":"Please close the door.","expectedAnswer":"Schließen Sie bitte die Tür."},
    {"id":74,"software":[{"german":"zuschließen","persian":"to lock"}],"promptFa":"I lock the door.","expectedAnswer":"Ich schließe die Tür zu."},
    {"id":75,"software":[],"promptFa":"Please lock the door.","expectedAnswer":"Schließen Sie bitte die Tür zu."},
    {"id":76,"software":[{"german":"zumachen","persian":"to close / shut"}],"promptFa":"I close the door.","expectedAnswer":"Ich mache die Tür zu."},
    {"id":77,"software":[{"german":"aufmachen","persian":"to open"},{"german":"Fenster","persian":"window"}],"promptFa":"I open the window.","expectedAnswer":"Ich mache das Fenster auf."},
    {"id":78,"software":[],"promptFa":"Please open the window.","expectedAnswer":"Machen Sie bitte das Fenster auf."},
    {"id":79,"software":[{"german":"mache","persian":"I make / do"}],"promptFa":"I close the door.","expectedAnswer":"Ich mache die Tür zu."},
    {"id":80,"software":[{"german":"Schloss","persian":"lock / castle"},{"german":"geschlossen","persian":"closed / locked"}],"promptFa":"The door is closed.","expectedAnswer":"Die Tür ist geschlossen."},
    {"id":81,"software":[],"promptFa":"Everything is closed today.","expectedAnswer":"Alles ist heute geschlossen."},
    {"id":82,"software":[],"promptFa":"Is the door closed?","expectedAnswer":"Ist die Tür geschlossen?"},
    {"id":83,"software":[{"german":"fangen","persian":"to catch"}],"promptFa":"I catch it.","expectedAnswer":"Ich fange es."},
    {"id":84,"software":[{"german":"anfangen","persian":"to begin / start"}],"promptFa":"We will start soon.","expectedAnswer":"Wir werden bald anfangen."},
    {"id":85,"software":[],"promptFa":"We are starting soon.","expectedAnswer":"Wir fangen bald an."},
    {"id":86,"software":[],"promptFa":"When are you starting?","expectedAnswer":"Wann fangen Sie an?"},
    {"id":87,"software":[],"promptFa":"When will you start?","expectedAnswer":"Wann werden Sie anfangen?"},
    {"id":88,"software":[{"german":"rufe","persian":"I call"}],"promptFa":"I will call you later.","expectedAnswer":"Ich rufe Sie später an."},
    {"id":89,"software":[],"promptFa":"Will you call me later?","expectedAnswer":"Werden Sie mich später anrufen?"},
    {"id":90,"software":[],"promptFa":"I will call you later and ask you.","expectedAnswer":"Ich werde Sie später anrufen und Sie fragen."},
    {"id":91,"software":[],"promptFa":"I am calling you to ask you something.","expectedAnswer":"Ich rufe Sie an, um Sie etwas zu fragen.","noteFa":"\"um ... zu + infinitive\" expresses purpose: \"in order to...\""},
    {"id":92,"software":[],"promptFa":"I will call you later to ask you whether you can come.","expectedAnswer":"Ich werde Sie später anrufen, um Sie zu fragen, ob Sie kommen können."},
    {"id":93,"software":[],"promptFa":"I will call you later to ask whether you can come with us this evening.","expectedAnswer":"Ich rufe Sie später an, um Sie zu fragen, ob Sie heute Abend mit uns kommen können."},
    {"id":94,"software":[{"german":"hoffen","persian":"to hope"}],"promptFa":"I hope.","expectedAnswer":"Ich hoffe."},
    {"id":95,"software":[{"german":"hoffe","persian":"I hope"},{"german":"dass","persian":"that"}],"promptFa":"I hope that I can do it.","expectedAnswer":"Ich hoffe, dass ich es tun kann.","noteFa":"\"dass\" introduces a subordinate clause. The conjugated verb goes to the end."},
    {"id":96,"software":[],"promptFa":"I hope that he will arrive tomorrow.","expectedAnswer":"Ich hoffe, dass er morgen ankommen wird."},
    {"id":97,"software":[],"promptFa":"I hope that you can come with us this evening.","expectedAnswer":"Ich hoffe, dass Sie heute Abend mit uns kommen können."},
    {"id":98,"software":[{"german":"denken","persian":"to think"}],"promptFa":"I think about it.","expectedAnswer":"Ich denke darüber."},
    {"id":99,"software":[{"german":"glauben","persian":"to believe / think"}],"promptFa":"I believe it.","expectedAnswer":"Ich glaube es."},
    {"id":100,"software":[{"german":"glaube","persian":"I believe / think"}],"promptFa":"I think that he will be here soon.","expectedAnswer":"Ich glaube, dass er bald hier sein wird."},
    {"id":101,"software":[],"promptFa":"I think that it will be ready tomorrow.","expectedAnswer":"Ich glaube, dass es morgen fertig sein wird."},
    {"id":102,"software":[],"promptFa":"I hope that it will be ready tomorrow.","expectedAnswer":"Ich hoffe, dass es morgen fertig sein wird."},
    {"id":103,"software":[{"german":"leicht","persian":"easy / light"}],"promptFa":"It is very easy.","expectedAnswer":"Es ist sehr leicht."},
    {"id":104,"software":[],"promptFa":"It is easy to do.","expectedAnswer":"Es ist leicht, es zu tun."},
    {"id":105,"software":[{"german":"schwer","persian":"difficult / heavy"}],"promptFa":"It is very difficult.","expectedAnswer":"Es ist sehr schwer."},
    {"id":106,"software":[],"promptFa":"It is difficult to understand.","expectedAnswer":"Es ist schwer zu verstehen."},
    {"id":107,"software":[{"german":"bequem","persian":"comfortable"}],"promptFa":"It is very comfortable here.","expectedAnswer":"Es ist sehr bequem hier."},
    {"id":108,"software":[],"promptFa":"Is it comfortable here?","expectedAnswer":"Ist es hier bequem?"},
    {"id":109,"software":[{"german":"nett","persian":"nice / pleasant"}],"promptFa":"It is very nice.","expectedAnswer":"Es ist sehr nett."},
    {"id":110,"software":[],"promptFa":"It is very nice here.","expectedAnswer":"Es ist sehr nett hier."},
    {"id":111,"software":[{"german":"gemütlich","persian":"cozy / comfortable"}],"promptFa":"It is very cozy here.","expectedAnswer":"Es ist sehr gemütlich hier."},
    {"id":112,"software":[],"promptFa":"I think it is very cozy here.","expectedAnswer":"Ich glaube, dass es hier sehr gemütlich ist."},
    {"id":113,"software":[{"german":"ein","persian":"a / one"},{"german":"Glas","persian":"glass"},{"german":"Wein","persian":"wine"}],"promptFa":"I want a glass of wine.","expectedAnswer":"Ich will ein Glas Wein."},
    {"id":114,"software":[{"german":"Rotwein","persian":"red wine"}],"promptFa":"I would like a glass of red wine.","expectedAnswer":"Ich möchte ein Glas Rotwein."},
    {"id":115,"software":[],"promptFa":"I would like a glass of red wine, please.","expectedAnswer":"Ich möchte bitte ein Glas Rotwein."},
    {"id":116,"software":[{"german":"Entschuldigung","persian":"excuse me / sorry"}],"promptFa":"Excuse me.","expectedAnswer":"Entschuldigung."},
    {"id":117,"software":[{"german":"entschuldigen","persian":"to excuse"}],"promptFa":"Excuse me, please.","expectedAnswer":"Entschuldigen Sie bitte."},
    {"id":118,"software":[{"german":"Verzeihung","persian":"excuse me / pardon"}],"promptFa":"Pardon me.","expectedAnswer":"Verzeihung."},
    {"id":119,"software":[],"promptFa":"Excuse me, may I ask you something?","expectedAnswer":"Entschuldigen Sie bitte, darf ich Sie etwas fragen?"},
    {"id":120,"software":[],"promptFa":"Excuse me, may I ask you where I can find it?","expectedAnswer":"Entschuldigen Sie bitte, darf ich Sie fragen, wo ich es finden kann?"},
    {"id":121,"software":[],"promptFa":"I will pick you up tomorrow morning.","expectedAnswer":"Ich werde Sie morgen früh abholen."},
    {"id":122,"software":[],"promptFa":"We would like to go out this evening.","expectedAnswer":"Wir möchten heute Abend ausgehen."},
    {"id":123,"software":[],"promptFa":"When will the train depart?","expectedAnswer":"Wann wird der Zug abfahren?"},
    {"id":124,"software":[],"promptFa":"I will arrive tomorrow afternoon.","expectedAnswer":"Ich werde morgen Nachmittag ankommen."},
    {"id":125,"software":[],"promptFa":"I will think about it and call you later.","expectedAnswer":"Ich werde es überlegen und Sie später anrufen."},
    {"id":126,"software":[],"promptFa":"Please come in and close the door.","expectedAnswer":"Kommen Sie bitte herein und schließen Sie die Tür."},
    {"id":127,"software":[],"promptFa":"Please open the window.","expectedAnswer":"Machen Sie bitte das Fenster auf."},
    {"id":128,"software":[],"promptFa":"We will start soon.","expectedAnswer":"Wir werden bald anfangen."},
    {"id":129,"software":[],"promptFa":"I will call you later to ask whether you can come.","expectedAnswer":"Ich werde Sie später anrufen, um Sie zu fragen, ob Sie kommen können."},
    {"id":130,"software":[],"promptFa":"I hope that you can come.","expectedAnswer":"Ich hoffe, dass Sie kommen können."},
    {"id":131,"software":[],"promptFa":"I think that he will arrive tomorrow.","expectedAnswer":"Ich glaube, dass er morgen ankommen wird."},
    {"id":132,"software":[],"promptFa":"I hope that everything will be ready tomorrow.","expectedAnswer":"Ich hoffe, dass morgen alles fertig sein wird."},
    {"id":133,"software":[],"promptFa":"It is easy to do, but it is difficult to explain.","expectedAnswer":"Es ist leicht, es zu tun, aber schwer zu erklären."},
    {"id":134,"software":[],"promptFa":"It is very comfortable and cozy here.","expectedAnswer":"Es ist hier sehr bequem und gemütlich."},
    {"id":135,"software":[],"promptFa":"Excuse me, I would like a glass of red wine.","expectedAnswer":"Entschuldigung, ich möchte ein Glas Rotwein."},
    {"id":136,"software":[],"promptFa":"I will never do it again.","expectedAnswer":"Ich werde es nie wieder tun."},
  ],
};
