// Lesson 3 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js - see main.js's INTERACTIVE_LESSONS
// map, which intercepts the "deutsch-almani-lektion-3" course card (a plain
// courses-table row, just for the level/title/grid-card metadata) and
// renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion3 = {
  id: 'lektion3',
  courseId: 'deutsch-almani-lektion-3',
  title: "Lektion 3 – Wohin, Warten, Imperativ und Zukunft",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-3-v1',
  promptLang: 'en',
  // Formal register throughout (Sie/Ihnen); "sie"/"er"/"es" also appear as
  // ordinary 3rd-person subject pronouns (he/she/it), unrelated to the
  // formal address form.
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"gehen","persian":"to go"}],"promptFa":"We are going.","expectedAnswer":"Wir gehen."},
    {"id":2,"software":[{"german":"wo","persian":"where"}],"promptFa":"Where are you?","expectedAnswer":"Wo sind Sie?"},
    {"id":3,"software":[{"german":"wohin","persian":"where to / to where"}],"promptFa":"Where are you going?","expectedAnswer":"Wohin gehen Sie?","noteFa":"\"wo\" asks about a location. \"wohin\" asks about movement toward a destination."},
    {"id":4,"software":[],"promptFa":"Where are we going?","expectedAnswer":"Wohin gehen wir?"},
    {"id":5,"software":[{"german":"wollen","persian":"to want"}],"promptFa":"Where do you want to go?","expectedAnswer":"Wohin wollen Sie gehen?"},
    {"id":6,"software":[],"promptFa":"I want to go.","expectedAnswer":"Ich will gehen."},
    {"id":7,"software":[{"german":"hingehen","persian":"to go there / to go to a place"}],"promptFa":"Where do you want to go?","expectedAnswer":"Wo wollen Sie hingehen?"},
    {"id":8,"software":[{"german":"dort","persian":"there"}],"promptFa":"It is there.","expectedAnswer":"Es ist dort."},
    {"id":9,"software":[{"german":"dorthin","persian":"to there / in that direction"}],"promptFa":"I want to go there.","expectedAnswer":"Ich will dorthin gehen.","noteFa":"\"dort\" describes a location. \"dorthin\" describes movement toward that location."},
    {"id":10,"software":[],"promptFa":"Do you want to go there?","expectedAnswer":"Wollen Sie dorthin gehen?"},
    {"id":11,"software":[{"german":"heute","persian":"today"},{"german":"können","persian":"can / to be able to"}],"promptFa":"I cannot go there today.","expectedAnswer":"Ich kann heute nicht dorthin gehen."},
    {"id":12,"software":[],"promptFa":"Can you go there today?","expectedAnswer":"Können Sie heute dorthin gehen?"},
    {"id":13,"software":[],"promptFa":"No, I cannot go there today.","expectedAnswer":"Nein, ich kann heute nicht dorthin gehen."},
    {"id":14,"software":[{"german":"morgen","persian":"tomorrow"}],"promptFa":"I can go there tomorrow.","expectedAnswer":"Ich kann morgen dorthin gehen."},
    {"id":15,"software":[],"promptFa":"Can you go there tomorrow?","expectedAnswer":"Können Sie morgen dorthin gehen?"},
    {"id":16,"software":[{"german":"beschäftigt","persian":"busy"}],"promptFa":"I am busy.","expectedAnswer":"Ich bin beschäftigt."},
    {"id":17,"software":[{"german":"sehr","persian":"very"}],"promptFa":"I am very busy.","expectedAnswer":"Ich bin sehr beschäftigt."},
    {"id":18,"software":[],"promptFa":"I am very busy today.","expectedAnswer":"Ich bin heute sehr beschäftigt."},
    {"id":19,"software":[{"german":"jetzt","persian":"now"}],"promptFa":"I am very busy now.","expectedAnswer":"Ich bin jetzt sehr beschäftigt."},
    {"id":20,"software":[],"promptFa":"I cannot go there because I am very busy.","expectedAnswer":"Ich kann nicht dorthin gehen, denn ich bin sehr beschäftigt."},
    {"id":21,"software":[],"promptFa":"I cannot go there today because I am very busy.","expectedAnswer":"Ich kann heute nicht dorthin gehen, denn ich bin sehr beschäftigt."},
    {"id":22,"software":[{"german":"werden","persian":"will / to become"}],"promptFa":"I will be busy.","expectedAnswer":"Ich werde beschäftigt sein.","noteFa":"Future tense can be formed with \"werden + infinitive\". The infinitive goes to the end."},
    {"id":23,"software":[],"promptFa":"I will be very busy.","expectedAnswer":"Ich werde sehr beschäftigt sein."},
    {"id":24,"software":[],"promptFa":"I will be very busy tomorrow.","expectedAnswer":"Ich werde morgen sehr beschäftigt sein."},
    {"id":25,"software":[],"promptFa":"I cannot go there tomorrow because I will be very busy.","expectedAnswer":"Ich kann morgen nicht dorthin gehen, denn ich werde sehr beschäftigt sein."},
    {"id":26,"software":[{"german":"das Geschäft","persian":"business / shop"}],"promptFa":null,"expectedAnswer":null},
    {"id":27,"software":[{"german":"bleiben","persian":"to stay"}],"promptFa":"We stay here.","expectedAnswer":"Wir bleiben hier."},
    {"id":28,"software":[{"german":"wie lange","persian":"how long"}],"promptFa":"How long are we staying?","expectedAnswer":"Wie lange bleiben wir?"},
    {"id":29,"software":[{"german":"hier","persian":"here"}],"promptFa":"How long are we staying here?","expectedAnswer":"Wie lange bleiben wir hier?"},
    {"id":30,"software":[],"promptFa":"How long can we stay here?","expectedAnswer":"Wie lange können wir hier bleiben?"},
    {"id":31,"software":[],"promptFa":"How long can we stay here today?","expectedAnswer":"Wie lange können wir heute hier bleiben?"},
    {"id":32,"software":[],"promptFa":"How long can you stay here?","expectedAnswer":"Wie lange können Sie hier bleiben?"},
    {"id":33,"software":[],"promptFa":"How long are you staying here?","expectedAnswer":"Wie lange bleiben Sie hier?"},
    {"id":34,"software":[],"promptFa":"How long will we stay here?","expectedAnswer":"Wie lange werden wir hier bleiben?"},
    {"id":35,"software":[],"promptFa":"How long will you stay here?","expectedAnswer":"Wie lange werden Sie hier bleiben?"},
    {"id":36,"software":[],"promptFa":"We will stay here today.","expectedAnswer":"Wir werden heute hier bleiben."},
    {"id":37,"software":[],"promptFa":"We cannot stay here for long today.","expectedAnswer":"Wir können heute nicht lange hier bleiben."},
    {"id":38,"software":[],"promptFa":"Come!","expectedAnswer":"Kommen Sie!","noteFa":"In the formal imperative with \"Sie\", the verb comes first: \"Kommen Sie!\", \"Warten Sie!\", \"Bringen Sie!\""},
    {"id":39,"software":[{"german":"hierher","persian":"to here / toward here"}],"promptFa":"Come here!","expectedAnswer":"Kommen Sie hierher!"},
    {"id":40,"software":[],"promptFa":"Please come here.","expectedAnswer":"Kommen Sie bitte hierher!"},
    {"id":41,"software":[{"german":"bringen","persian":"to bring"},{"german":"mir","persian":"to me"}],"promptFa":"Bring it to me!","expectedAnswer":"Bringen Sie es mir!"},
    {"id":42,"software":[],"promptFa":"Bring it to me today!","expectedAnswer":"Bringen Sie es mir heute!"},
    {"id":43,"software":[{"german":"morgen","persian":"tomorrow"}],"promptFa":"Bring it to me tomorrow!","expectedAnswer":"Bringen Sie es mir morgen!"},
    {"id":44,"software":[],"promptFa":"Are you bringing it to me today?","expectedAnswer":"Bringen Sie es mir heute?","noteFa":"Compare the statement/question and imperative. \"Bringen Sie...?\" can be a question with question intonation; \"Bringen Sie...!\" is a formal command."},
    {"id":45,"software":[],"promptFa":"Bring it to me today!","expectedAnswer":"Bringen Sie es mir heute!"},
    {"id":46,"software":[{"german":"warten","persian":"to wait"}],"promptFa":"I am waiting.","expectedAnswer":"Ich warte."},
    {"id":47,"software":[],"promptFa":"Why are you waiting?","expectedAnswer":"Warum warten Sie?"},
    {"id":48,"software":[],"promptFa":"Wait!","expectedAnswer":"Warten Sie!"},
    {"id":49,"software":[{"german":"bitte","persian":"please"}],"promptFa":"Please wait!","expectedAnswer":"Warten Sie bitte!"},
    {"id":50,"software":[],"promptFa":"Would you please wait?","expectedAnswer":"Wollen Sie bitte warten?"},
    {"id":51,"software":[{"german":"warten auf","persian":"to wait for"}],"promptFa":"I am waiting for you.","expectedAnswer":"Ich warte auf Sie.","noteFa":"\"warten auf\" is learned as one unit: \"auf jemanden warten\" = to wait for someone."},
    {"id":52,"software":[],"promptFa":"Wait for me!","expectedAnswer":"Warten Sie auf mich!"},
    {"id":53,"software":[],"promptFa":"Are you waiting for me?","expectedAnswer":"Warten Sie auf mich?"},
    {"id":54,"software":[],"promptFa":"Can you wait for me?","expectedAnswer":"Können Sie auf mich warten?"},
    {"id":55,"software":[],"promptFa":"Do you want to wait for me?","expectedAnswer":"Wollen Sie auf mich warten?"},
    {"id":56,"software":[],"promptFa":"Would you please wait for me?","expectedAnswer":"Wollen Sie bitte auf mich warten?"},
    {"id":57,"software":[{"german":"wo","persian":"where"}],"promptFa":"Where do you want to wait for me?","expectedAnswer":"Wo wollen Sie auf mich warten?"},
    {"id":58,"software":[],"promptFa":"Where will you wait for me?","expectedAnswer":"Wo werden Sie auf mich warten?"},
    {"id":59,"software":[],"promptFa":"Will you wait for me here?","expectedAnswer":"Werden Sie hier auf mich warten?"},
    {"id":60,"software":[],"promptFa":"Will you wait for me here tomorrow?","expectedAnswer":"Werden Sie morgen hier auf mich warten?"},
    {"id":61,"software":[],"promptFa":"Would you please wait for me here tomorrow?","expectedAnswer":"Wollen Sie bitte morgen hier auf mich warten?"},
    {"id":62,"software":[],"promptFa":"I will wait for you.","expectedAnswer":"Ich werde auf Sie warten."},
    {"id":63,"software":[],"promptFa":"I will wait for you here.","expectedAnswer":"Ich werde hier auf Sie warten."},
    {"id":64,"software":[],"promptFa":"I will wait for you here tomorrow.","expectedAnswer":"Ich werde morgen hier auf Sie warten."},
    {"id":65,"software":[{"german":"mit Ihnen","persian":"with you, formal"}],"promptFa":"I am coming with you.","expectedAnswer":"Ich komme mit Ihnen."},
    {"id":66,"software":[],"promptFa":"I will come with you.","expectedAnswer":"Ich werde mit Ihnen kommen."},
    {"id":67,"software":[],"promptFa":"I will stay here.","expectedAnswer":"Ich werde hier bleiben."},
    {"id":68,"software":[],"promptFa":"I will wait here.","expectedAnswer":"Ich werde hier warten."},
    {"id":69,"software":[],"promptFa":"I will stay here and wait for you.","expectedAnswer":"Ich werde hier bleiben und auf Sie warten."},
    {"id":70,"software":[{"german":"kaufen","persian":"to buy"}],"promptFa":"I buy it.","expectedAnswer":"Ich kaufe es."},
    {"id":71,"software":[],"promptFa":"I will buy it.","expectedAnswer":"Ich werde es kaufen."},
    {"id":72,"software":[{"german":"teuer","persian":"expensive"}],"promptFa":"It is expensive.","expectedAnswer":"Es ist teuer."},
    {"id":73,"software":[],"promptFa":"It is very expensive.","expectedAnswer":"Es ist sehr teuer."},
    {"id":74,"software":[{"german":"denn","persian":"because"}],"promptFa":"We will not buy it because it is very expensive.","expectedAnswer":"Wir werden es nicht kaufen, denn es ist sehr teuer.","noteFa":"After \"denn\", normal main-clause word order remains: \"denn es ist...\" The verb does not move to the end."},
    {"id":75,"software":[],"promptFa":"We want to have it.","expectedAnswer":"Wir wollen es haben."},
    {"id":76,"software":[],"promptFa":"We will buy it because we want to have it.","expectedAnswer":"Wir werden es kaufen, denn wir wollen es haben."},
    {"id":77,"software":[],"promptFa":"I will not buy it because it is very expensive.","expectedAnswer":"Ich werde es nicht kaufen, denn es ist sehr teuer."},
    {"id":78,"software":[],"promptFa":"Will you buy it?","expectedAnswer":"Werden Sie es kaufen?"},
    {"id":79,"software":[],"promptFa":"Why will you not buy it?","expectedAnswer":"Warum werden Sie es nicht kaufen?"},
    {"id":80,"software":[],"promptFa":"I will not buy it because it is very expensive.","expectedAnswer":"Ich werde es nicht kaufen, denn es ist sehr teuer."},
    {"id":81,"software":[],"promptFa":"I will see you tomorrow.","expectedAnswer":"Ich sehe Sie morgen.","noteFa":"German often uses the present tense for future events when a future time expression such as \"morgen\" makes the meaning clear."},
    {"id":82,"software":[],"promptFa":"I am going with you tomorrow.","expectedAnswer":"Ich gehe morgen mit Ihnen."},
    {"id":83,"software":[],"promptFa":"I will see you tomorrow.","expectedAnswer":"Ich werde Sie morgen sehen.","noteFa":"Compare: \"Ich sehe Sie morgen.\" and \"Ich werde Sie morgen sehen.\" Both can refer to the future."},
    {"id":84,"software":[],"promptFa":"I will go with you tomorrow.","expectedAnswer":"Ich werde morgen mit Ihnen gehen."},
    {"id":85,"software":[{"german":"er","persian":"he"},{"german":"sie","persian":"she"},{"german":"es","persian":"it"},{"german":"wird","persian":"will, for er/sie/es"}],"promptFa":null,"expectedAnswer":null},
    {"id":86,"software":[],"promptFa":"He will buy it.","expectedAnswer":"Er wird es kaufen."},
    {"id":87,"software":[],"promptFa":"She will buy it.","expectedAnswer":"Sie wird es kaufen."},
    {"id":88,"software":[],"promptFa":"He will be here soon.","expectedAnswer":"Er wird bald hier sein."},
    {"id":89,"software":[],"promptFa":"She will be here soon.","expectedAnswer":"Sie wird bald hier sein."},
    {"id":90,"software":[{"german":"bald","persian":"soon"}],"promptFa":"He is coming soon.","expectedAnswer":"Er kommt bald."},
    {"id":91,"software":[],"promptFa":"She is coming soon.","expectedAnswer":"Sie kommt bald.","noteFa":"The present tense can also express a planned future: \"Er kommt bald.\""},
    {"id":92,"software":[{"german":"fertig","persian":"ready / finished"}],"promptFa":"It is ready.","expectedAnswer":"Es ist fertig."},
    {"id":93,"software":[{"german":"schon","persian":"already"}],"promptFa":"It is already ready.","expectedAnswer":"Es ist schon fertig."},
    {"id":94,"software":[],"promptFa":"It is already here.","expectedAnswer":"Es ist schon hier."},
    {"id":95,"software":[],"promptFa":"I already have it.","expectedAnswer":"Ich habe es schon."},
    {"id":96,"software":[],"promptFa":"Do you already have it?","expectedAnswer":"Haben Sie es schon?"},
    {"id":97,"software":[],"promptFa":"Is it already ready?","expectedAnswer":"Ist es schon fertig?"},
    {"id":98,"software":[{"german":"schön","persian":"beautiful / nice"}],"promptFa":"It is very beautiful.","expectedAnswer":"Es ist sehr schön."},
    {"id":99,"software":[],"promptFa":"He is very handsome.","expectedAnswer":"Er ist sehr schön."},
    {"id":100,"software":[{"german":"alles","persian":"everything"}],"promptFa":"Everything is ready.","expectedAnswer":"Alles ist fertig."},
    {"id":101,"software":[],"promptFa":"Everything is already ready.","expectedAnswer":"Alles ist schon fertig."},
    {"id":102,"software":[],"promptFa":"Everything is already here.","expectedAnswer":"Alles ist schon hier."},
    {"id":103,"software":[],"promptFa":"Everything will be ready soon.","expectedAnswer":"Alles wird bald fertig sein."},
    {"id":104,"software":[{"german":"für Sie","persian":"for you, formal"}],"promptFa":"Everything will be ready for you soon.","expectedAnswer":"Alles wird für Sie bald fertig sein."},
    {"id":105,"software":[],"promptFa":"Is everything already ready?","expectedAnswer":"Ist alles schon fertig?"},
    {"id":106,"software":[{"german":"bleiben","persian":"to stay"}],"promptFa":"He stays.","expectedAnswer":"Er bleibt."},
    {"id":107,"software":[],"promptFa":"She stays.","expectedAnswer":"Sie bleibt."},
    {"id":108,"software":[],"promptFa":"It stays here.","expectedAnswer":"Es bleibt hier."},
    {"id":109,"software":[],"promptFa":"Everything stays here.","expectedAnswer":"Alles bleibt hier."},
    {"id":110,"software":[{"german":"alle","persian":"everyone / all"}],"promptFa":"Everyone stays here.","expectedAnswer":"Alle bleiben hier."},
    {"id":111,"software":[{"german":"mein Freund","persian":"my friend"}],"promptFa":"My friend stays here.","expectedAnswer":"Mein Freund bleibt hier."},
    {"id":112,"software":[{"german":"nicht","persian":"not"}],"promptFa":"My friend does not stay here.","expectedAnswer":"Mein Freund bleibt nicht hier."},
    {"id":113,"software":[{"german":"meine Freunde","persian":"my friends"}],"promptFa":"My friends stay here.","expectedAnswer":"Meine Freunde bleiben hier."},
    {"id":114,"software":[],"promptFa":"My friends do not stay here.","expectedAnswer":"Meine Freunde bleiben nicht hier."},
    {"id":115,"software":[{"german":"wir alle","persian":"all of us / we all"}],"promptFa":"We all stay here.","expectedAnswer":"Wir alle bleiben hier."},
    {"id":116,"software":[],"promptFa":"We will all stay here.","expectedAnswer":"Wir werden alle hier bleiben."},
    {"id":117,"software":[],"promptFa":"How long will we all stay here?","expectedAnswer":"Wie lange werden wir alle hier bleiben?"},
    {"id":118,"software":[],"promptFa":"My friend will come tomorrow.","expectedAnswer":"Mein Freund wird morgen kommen."},
    {"id":119,"software":[],"promptFa":"My friends will come tomorrow.","expectedAnswer":"Meine Freunde werden morgen kommen."},
    {"id":120,"software":[],"promptFa":"He brings it to me.","expectedAnswer":"Er bringt es mir."},
    {"id":121,"software":[{"german":"Ihnen","persian":"to you, formal"}],"promptFa":"He brings it to you.","expectedAnswer":"Er bringt es Ihnen."},
    {"id":122,"software":[],"promptFa":"He will bring it to you.","expectedAnswer":"Er wird es Ihnen bringen."},
    {"id":123,"software":[],"promptFa":"He will bring it to you tomorrow.","expectedAnswer":"Er wird es Ihnen morgen bringen."},
    {"id":124,"software":[],"promptFa":"When will he bring it to you?","expectedAnswer":"Wann wird er es Ihnen bringen?"},
    {"id":125,"software":[],"promptFa":"When will you bring it to me?","expectedAnswer":"Wann werden Sie es mir bringen?"},
    {"id":126,"software":[],"promptFa":"Can you bring it to me?","expectedAnswer":"Können Sie es mir bringen?"},
    {"id":127,"software":[],"promptFa":"Can you bring it to me tomorrow?","expectedAnswer":"Können Sie es mir morgen bringen?"},
    {"id":128,"software":[],"promptFa":"Would you please bring it to me?","expectedAnswer":"Wollen Sie es mir bitte bringen?"},
    {"id":129,"software":[],"promptFa":"Would you please bring it to me tomorrow?","expectedAnswer":"Wollen Sie es mir bitte morgen bringen?"},
    {"id":130,"software":[],"promptFa":"Bring it to me tomorrow, please.","expectedAnswer":"Bringen Sie es mir morgen, bitte!"},
    {"id":131,"software":[],"promptFa":"When will you bring it to me?","expectedAnswer":"Wann werden Sie es mir bringen?"},
    {"id":132,"software":[],"promptFa":"Where are you going?","expectedAnswer":"Wohin gehen Sie?","noteFa":"Repetition: \"wo\" = location, \"wohin\" = destination, \"dort\" = there, \"dorthin\" = to there."},
    {"id":133,"software":[],"promptFa":"Where are you waiting?","expectedAnswer":"Wo warten Sie?"},
    {"id":134,"software":[],"promptFa":"I am waiting there.","expectedAnswer":"Ich warte dort."},
    {"id":135,"software":[],"promptFa":"I am going there.","expectedAnswer":"Ich gehe dorthin."},
    {"id":136,"software":[],"promptFa":"Where will you wait for me?","expectedAnswer":"Wo werden Sie auf mich warten?"},
    {"id":137,"software":[],"promptFa":"Where will you go tomorrow?","expectedAnswer":"Wohin werden Sie morgen gehen?"},
    {"id":138,"software":[],"promptFa":"I can go there.","expectedAnswer":"Ich kann dorthin gehen.","noteFa":"Repetition: modal verb + infinitive. The infinitive goes to the end."},
    {"id":139,"software":[],"promptFa":"I want to stay here.","expectedAnswer":"Ich will hier bleiben."},
    {"id":140,"software":[],"promptFa":"Can you wait for me?","expectedAnswer":"Können Sie auf mich warten?"},
    {"id":141,"software":[],"promptFa":"Do you want to buy it?","expectedAnswer":"Wollen Sie es kaufen?"},
    {"id":142,"software":[],"promptFa":"We cannot stay here for long.","expectedAnswer":"Wir können nicht lange hier bleiben."},
    {"id":143,"software":[],"promptFa":"I will stay here.","expectedAnswer":"Ich werde hier bleiben.","noteFa":"Repetition: future \"werden + infinitive\"."},
    {"id":144,"software":[],"promptFa":"I will wait for you.","expectedAnswer":"Ich werde auf Sie warten."},
    {"id":145,"software":[],"promptFa":"He will buy it.","expectedAnswer":"Er wird es kaufen."},
    {"id":146,"software":[],"promptFa":"We will not buy it.","expectedAnswer":"Wir werden es nicht kaufen."},
    {"id":147,"software":[],"promptFa":"They will stay here.","expectedAnswer":"Sie werden hier bleiben."},
    {"id":148,"software":[],"promptFa":"I cannot go there today because I am very busy.","expectedAnswer":"Ich kann heute nicht dorthin gehen, denn ich bin sehr beschäftigt.","noteFa":"Final practical drill: combine destination, time, and reason."},
    {"id":149,"software":[],"promptFa":"But I can go there tomorrow.","expectedAnswer":"Aber ich kann morgen dorthin gehen."},
    {"id":150,"software":[],"promptFa":"I will be there tomorrow.","expectedAnswer":"Ich werde morgen dort sein."},
    {"id":151,"software":[],"promptFa":"Will you wait for me there?","expectedAnswer":"Werden Sie dort auf mich warten?"},
    {"id":152,"software":[],"promptFa":"Yes, I will wait for you there.","expectedAnswer":"Ja, ich werde dort auf Sie warten."},
    {"id":153,"software":[],"promptFa":"How long will you stay there?","expectedAnswer":"Wie lange werden Sie dort bleiben?"},
    {"id":154,"software":[],"promptFa":"I will not stay there for long.","expectedAnswer":"Ich werde dort nicht lange bleiben."},
    {"id":155,"software":[],"promptFa":"Please bring it to me tomorrow.","expectedAnswer":"Bringen Sie es mir morgen, bitte!"},
    {"id":156,"software":[],"promptFa":"I will bring it to you tomorrow.","expectedAnswer":"Ich werde es Ihnen morgen bringen."},
    {"id":157,"software":[],"promptFa":"Everything will be ready for you tomorrow.","expectedAnswer":"Alles wird morgen für Sie fertig sein."},
  ],
};
