// Lesson 6 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/lektion3.js/lektion4.js/lektion5.js -
// see main.js's INTERACTIVE_LESSONS map, which intercepts the
// "deutsch-almani-lektion-6" course card (a plain courses-table row, just for
// the level/title/grid-card metadata) and renders this instead of the plain
// page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion6 = {
  id: 'lektion6',
  courseId: 'deutsch-almani-lektion-6',
  title: "Lektion 6 – Telefonieren, Sprechen, Würde, Ob und Seit",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-6-v1',
  promptLang: 'en',
  // Formal register throughout (Sie/Ihnen).
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"später","persian":"later"}],"promptFa":"I will do it later.","expectedAnswer":"Ich werde es später tun."},
    {"id":2,"software":[],"promptFa":"I will do it a little later.","expectedAnswer":"Ich werde es etwas später tun."},
    {"id":3,"software":[],"promptFa":"Can you do it later?","expectedAnswer":"Können Sie es später tun?"},
    {"id":4,"software":[{"german":"rufen","persian":"to call / to shout"}],"promptFa":"I will call.","expectedAnswer":"Ich werde rufen."},
    {"id":5,"software":[{"german":"anrufen","persian":"to call someone by phone"}],"promptFa":"I will call you later.","expectedAnswer":"Ich werde Sie später anrufen."},
    {"id":6,"software":[],"promptFa":"Would you like to call me later?","expectedAnswer":"Wollen Sie mich später anrufen?"},
    {"id":7,"software":[],"promptFa":"Can you call me later?","expectedAnswer":"Können Sie mich später anrufen?"},
    {"id":8,"software":[],"promptFa":"I cannot call you now, but I will call you later.","expectedAnswer":"Ich kann Sie jetzt nicht anrufen, aber ich werde Sie später anrufen."},
    {"id":9,"software":[{"german":"fahren","persian":"to go / travel by vehicle"}],"promptFa":"I am going to Berlin.","expectedAnswer":"Ich fahre nach Berlin."},
    {"id":10,"software":[{"german":"fahre","persian":"I go / I travel by vehicle"}],"promptFa":"I am going to Berlin today.","expectedAnswer":"Ich fahre heute nach Berlin."},
    {"id":11,"software":[{"german":"Berlin","persian":"Berlin"}],"promptFa":"I would like to go to Berlin.","expectedAnswer":"Ich möchte nach Berlin fahren."},
    {"id":12,"software":[{"german":"Deutschland","persian":"Germany"}],"promptFa":"I am going to Germany.","expectedAnswer":"Ich fahre nach Deutschland."},
    {"id":13,"software":[],"promptFa":"I will go to Germany tomorrow.","expectedAnswer":"Ich werde morgen nach Deutschland fahren."},
    {"id":14,"software":[{"german":"Deutsch","persian":"German"}],"promptFa":"I understand German.","expectedAnswer":"Ich verstehe Deutsch."},
    {"id":15,"software":[{"german":"sprechen","persian":"to speak"},{"german":"Englisch","persian":"English"}],"promptFa":"You speak English.","expectedAnswer":"Sie sprechen Englisch."},
    {"id":16,"software":[],"promptFa":"Do you speak English?","expectedAnswer":"Sprechen Sie Englisch?"},
    {"id":17,"software":[],"promptFa":"Do you speak German?","expectedAnswer":"Sprechen Sie Deutsch?"},
    {"id":18,"software":[],"promptFa":"You speak German very well.","expectedAnswer":"Sie sprechen Deutsch sehr gut."},
    {"id":19,"software":[],"promptFa":"I would like to speak German very well.","expectedAnswer":"Ich möchte Deutsch sehr gut sprechen."},
    {"id":20,"software":[],"promptFa":"Can you speak German?","expectedAnswer":"Können Sie Deutsch sprechen?"},
    {"id":21,"software":[{"german":"sagt","persian":"says"}],"promptFa":"He says it.","expectedAnswer":"Er sagt es."},
    {"id":22,"software":[],"promptFa":"How does one say it in German?","expectedAnswer":"Wie sagt man es auf Deutsch?"},
    {"id":23,"software":[],"promptFa":"How do you say it in German?","expectedAnswer":"Wie sagen Sie es auf Deutsch?"},
    {"id":24,"software":[],"promptFa":"One does not say it like that.","expectedAnswer":"Man sagt es nicht so."},
    {"id":25,"software":[],"promptFa":"Does one say it like that?","expectedAnswer":"Sagt man es so?"},
    {"id":26,"software":[],"promptFa":"How does one say that in German?","expectedAnswer":"Wie sagt man das auf Deutsch?"},
    {"id":27,"software":[],"promptFa":"It is too late.","expectedAnswer":"Es ist zu spät."},
    {"id":28,"software":[],"promptFa":"It is too late to do it now.","expectedAnswer":"Es ist zu spät, es jetzt zu tun."},
    {"id":29,"software":[],"promptFa":"I will do it later.","expectedAnswer":"Ich werde es später tun."},
    {"id":30,"software":[],"promptFa":"I will do it later today.","expectedAnswer":"Ich werde es heute später tun."},
    {"id":31,"software":[],"promptFa":"It will not be possible to do it now.","expectedAnswer":"Es wird nicht möglich sein, es jetzt zu tun."},
    {"id":32,"software":[],"promptFa":"It will be very important to do it.","expectedAnswer":"Es wird sehr wichtig sein, es zu tun."},
    {"id":33,"software":[],"promptFa":"I have no time to do it now.","expectedAnswer":"Ich habe keine Zeit, es jetzt zu tun."},
    {"id":34,"software":[],"promptFa":"I will not have time to do it today.","expectedAnswer":"Ich werde nicht die Zeit haben, es heute zu tun."},
    {"id":35,"software":[{"german":"würde","persian":"would"}],"promptFa":"I would do it.","expectedAnswer":"Ich würde es tun.","noteFa":"\"würde + infinitive\" is commonly used to express a hypothetical or conditional action."},
    {"id":36,"software":[],"promptFa":"He would do it.","expectedAnswer":"Er würde es tun."},
    {"id":37,"software":[],"promptFa":"I would buy it.","expectedAnswer":"Ich würde es kaufen."},
    {"id":38,"software":[],"promptFa":"I would not buy it.","expectedAnswer":"Ich würde es nicht kaufen."},
    {"id":39,"software":[{"german":"würden","persian":"would, plural/formal"}],"promptFa":"We would do it.","expectedAnswer":"Wir würden es tun."},
    {"id":40,"software":[],"promptFa":"We would not do it.","expectedAnswer":"Wir würden es nicht tun."},
    {"id":41,"software":[],"promptFa":"Would you do it?","expectedAnswer":"Würden Sie es tun?"},
    {"id":42,"software":[],"promptFa":"Would you buy it?","expectedAnswer":"Würden Sie es kaufen?"},
    {"id":43,"software":[],"promptFa":"It would not be possible.","expectedAnswer":"Es würde nicht möglich sein."},
    {"id":44,"software":[],"promptFa":"It would not be possible to do it.","expectedAnswer":"Es würde nicht möglich sein, es zu tun."},
    {"id":45,"software":[],"promptFa":"I would do it if I had time.","expectedAnswer":"Ich würde es tun, wenn ich Zeit hätte."},
    {"id":46,"software":[],"promptFa":"I would buy it if I had the opportunity.","expectedAnswer":"Ich würde es kaufen, wenn ich die Gelegenheit hätte."},
    {"id":47,"software":[],"promptFa":"I would not do it today.","expectedAnswer":"Ich würde es heute nicht tun."},
    {"id":48,"software":[],"promptFa":"I would not do it today because I would have no time.","expectedAnswer":"Ich würde es heute nicht tun, weil ich keine Zeit haben würde."},
    {"id":49,"software":[],"promptFa":"I would like to know when it will be ready.","expectedAnswer":"Ich möchte wissen, wann es fertig sein wird."},
    {"id":50,"software":[],"promptFa":"It could be ready today.","expectedAnswer":"Es kann heute fertig sein."},
    {"id":51,"software":[],"promptFa":"It will be ready today.","expectedAnswer":"Es wird heute fertig sein."},
    {"id":52,"software":[],"promptFa":"I want to know at what time it will be ready.","expectedAnswer":"Ich will wissen, um wie viel Uhr es fertig sein wird."},
    {"id":53,"software":[],"promptFa":"I would like to know at what time it will be ready.","expectedAnswer":"Ich möchte wissen, um wie viel Uhr es fertig sein wird."},
    {"id":54,"software":[],"promptFa":"I would like to know why it cannot be ready today.","expectedAnswer":"Ich möchte wissen, warum es heute nicht fertig sein kann."},
    {"id":55,"software":[],"promptFa":"We do not want to do it today.","expectedAnswer":"Wir wollen es heute nicht tun."},
    {"id":56,"software":[],"promptFa":"I would like to know when you want to do it.","expectedAnswer":"Ich möchte wissen, wann Sie es tun wollen."},
    {"id":57,"software":[],"promptFa":"I would like to know at what time he can do it.","expectedAnswer":"Ich möchte wissen, um wie viel Uhr er es tun kann."},
    {"id":58,"software":[],"promptFa":"I will wait here if you want.","expectedAnswer":"Ich werde hier warten, wenn Sie wollen."},
    {"id":59,"software":[],"promptFa":"I will wait for you here if you want.","expectedAnswer":"Ich werde hier auf Sie warten, wenn Sie wollen."},
    {"id":60,"software":[{"german":"ob","persian":"whether / if"}],"promptFa":"I do not know whether I can do it.","expectedAnswer":"Ich weiß nicht, ob ich es tun kann.","noteFa":"\"ob\" introduces an indirect yes/no question."},
    {"id":61,"software":[],"promptFa":"Do you know whether it is possible?","expectedAnswer":"Wissen Sie, ob es möglich ist?"},
    {"id":62,"software":[],"promptFa":"Can you tell me whether you can do it?","expectedAnswer":"Können Sie mir sagen, ob Sie es tun können?"},
    {"id":63,"software":[],"promptFa":"I would like to know whether you can do it.","expectedAnswer":"Ich möchte wissen, ob Sie es tun können."},
    {"id":64,"software":[],"promptFa":"I do not know whether it will be possible.","expectedAnswer":"Ich weiß nicht, ob es möglich sein wird."},
    {"id":65,"software":[{"german":"versuchen","persian":"to try"}],"promptFa":"I will try.","expectedAnswer":"Ich werde versuchen."},
    {"id":66,"software":[],"promptFa":"I do not know whether I can do it, but I will try.","expectedAnswer":"Ich weiß nicht, ob ich es tun kann, aber ich werde versuchen."},
    {"id":67,"software":[],"promptFa":"I do not know whether it is possible, but I will try.","expectedAnswer":"Ich weiß nicht, ob es möglich ist, aber ich werde versuchen."},
    {"id":68,"software":[],"promptFa":"I do not know whether it will be possible to do it.","expectedAnswer":"Ich weiß nicht, ob es möglich sein wird, es zu tun."},
    {"id":69,"software":[],"promptFa":"I do not know whether I will have the opportunity to go there today.","expectedAnswer":"Ich weiß nicht, ob ich die Gelegenheit haben werde, heute dorthin zu gehen."},
    {"id":70,"software":[{"german":"suchen","persian":"to search / look for"}],"promptFa":"I am looking for it.","expectedAnswer":"Ich suche es."},
    {"id":71,"software":[],"promptFa":"I cannot find it, but I will look for it.","expectedAnswer":"Ich kann es nicht finden, aber ich werde es suchen."},
    {"id":72,"software":[],"promptFa":"Are you looking for it?","expectedAnswer":"Suchen Sie es?"},
    {"id":73,"software":[],"promptFa":"What are you looking for?","expectedAnswer":"Was suchen Sie?"},
    {"id":74,"software":[],"promptFa":"I will look for it and call you later.","expectedAnswer":"Ich werde es suchen und Sie später anrufen."},
    {"id":75,"software":[{"german":"seit","persian":"since / for, continuing until now"},{"german":"zehn","persian":"ten"},{"german":"Minuten","persian":"minutes"}],"promptFa":"I have been waiting for ten minutes.","expectedAnswer":"Ich warte seit zehn Minuten.","noteFa":"\"seit\" describes something that started in the past and is still continuing. German normally uses the present tense with it."},
    {"id":76,"software":[{"german":"warte","persian":"I wait / I am waiting"}],"promptFa":"I have been waiting here for ten minutes.","expectedAnswer":"Ich warte hier seit zehn Minuten."},
    {"id":77,"software":[],"promptFa":"How long have you been waiting?","expectedAnswer":"Wie lange warten Sie schon?"},
    {"id":78,"software":[],"promptFa":"I have been waiting for you for ten minutes.","expectedAnswer":"Ich warte seit zehn Minuten auf Sie."},
    {"id":79,"software":[{"german":"wohnen","persian":"to live / reside"}],"promptFa":"I live here.","expectedAnswer":"Ich wohne hier."},
    {"id":80,"software":[{"german":"wohne","persian":"I live / reside"}],"promptFa":"I have lived here for ten years.","expectedAnswer":"Ich wohne hier seit zehn Jahren."},
    {"id":81,"software":[{"german":"Jahren","persian":"years, dative plural"}],"promptFa":"I have already lived here for ten years.","expectedAnswer":"Ich wohne hier schon seit zehn Jahren."},
    {"id":82,"software":[],"promptFa":"How long have you lived here?","expectedAnswer":"Wie lange wohnen Sie schon hier?"},
    {"id":83,"software":[],"promptFa":"Have you lived here for a long time?","expectedAnswer":"Wohnen Sie schon lange hier?"},
    {"id":84,"software":[{"german":"sind","persian":"are"}],"promptFa":"How long have you been here?","expectedAnswer":"Wie lange sind Sie schon hier?"},
    {"id":85,"software":[],"promptFa":"We have been here for ten minutes.","expectedAnswer":"Wir sind seit zehn Minuten hier."},
    {"id":86,"software":[{"german":"arbeiten","persian":"to work"}],"promptFa":"I work here.","expectedAnswer":"Ich arbeite hier."},
    {"id":87,"software":[{"german":"die Arbeit","persian":"work"}],"promptFa":"The work is very important.","expectedAnswer":"Die Arbeit ist sehr wichtig."},
    {"id":88,"software":[{"german":"arbeitet","persian":"works"}],"promptFa":"He works here.","expectedAnswer":"Er arbeitet hier."},
    {"id":89,"software":[{"german":"langer","persian":"long, in \"seit langer Zeit\""}],"promptFa":"He has been working here for a long time.","expectedAnswer":"Er arbeitet hier schon seit langer Zeit."},
    {"id":90,"software":[],"promptFa":"How long has he been working here?","expectedAnswer":"Wie lange arbeitet er schon hier?"},
    {"id":91,"software":[],"promptFa":"She has been working here for a long time.","expectedAnswer":"Sie arbeitet hier schon seit langer Zeit."},
    {"id":92,"software":[{"german":"drei","persian":"three"},{"german":"Tagen","persian":"days, dative plural"}],"promptFa":"We have been here for three days.","expectedAnswer":"Wir sind seit drei Tagen hier."},
    {"id":93,"software":[],"promptFa":"We have already been here for three days.","expectedAnswer":"Wir sind schon seit drei Tagen hier."},
    {"id":94,"software":[],"promptFa":"They have been here for three days.","expectedAnswer":"Sie sind seit drei Tagen hier."},
    {"id":95,"software":[],"promptFa":"I have been working here for three days.","expectedAnswer":"Ich arbeite seit drei Tagen hier."},
    {"id":96,"software":[],"promptFa":"He has been working here for ten years.","expectedAnswer":"Er arbeitet seit zehn Jahren hier."},
    {"id":97,"software":[],"promptFa":"I have lived in Germany for ten years.","expectedAnswer":"Ich wohne seit zehn Jahren in Deutschland."},
    {"id":98,"software":[],"promptFa":"I have been learning German for three years.","expectedAnswer":"Ich lerne seit drei Jahren Deutsch."},
    {"id":99,"software":[],"promptFa":"I speak German, but I would like to speak it better.","expectedAnswer":"Ich spreche Deutsch, aber ich möchte es besser sprechen."},
    {"id":100,"software":[],"promptFa":"How do you say that in German?","expectedAnswer":"Wie sagt man das auf Deutsch?"},
    {"id":101,"software":[],"promptFa":"I do not know, but I will try.","expectedAnswer":"Ich weiß es nicht, aber ich werde versuchen."},
    {"id":102,"software":[],"promptFa":"I would do it later if I had time.","expectedAnswer":"Ich würde es später tun, wenn ich Zeit hätte."},
    {"id":103,"software":[],"promptFa":"I do not know whether I will have time later.","expectedAnswer":"Ich weiß nicht, ob ich später Zeit haben werde."},
    {"id":104,"software":[],"promptFa":"If I have time, I will call you later.","expectedAnswer":"Wenn ich Zeit habe, werde ich Sie später anrufen."},
    {"id":105,"software":[],"promptFa":"Can you call me later if you have time?","expectedAnswer":"Können Sie mich später anrufen, wenn Sie Zeit haben?"},
    {"id":106,"software":[],"promptFa":"I am going to Berlin tomorrow.","expectedAnswer":"Ich fahre morgen nach Berlin."},
    {"id":107,"software":[],"promptFa":"I would like to know whether you are going to Berlin tomorrow.","expectedAnswer":"Ich möchte wissen, ob Sie morgen nach Berlin fahren."},
    {"id":108,"software":[],"promptFa":"Do you speak German?","expectedAnswer":"Sprechen Sie Deutsch?"},
    {"id":109,"software":[],"promptFa":"Yes, I speak German, but not very well.","expectedAnswer":"Ja, ich spreche Deutsch, aber nicht sehr gut."},
    {"id":110,"software":[],"promptFa":"How long have you lived in Germany?","expectedAnswer":"Wie lange wohnen Sie schon in Deutschland?"},
    {"id":111,"software":[],"promptFa":"I have lived in Germany for three years.","expectedAnswer":"Ich wohne seit drei Jahren in Deutschland."},
    {"id":112,"software":[],"promptFa":"How long have you been working here?","expectedAnswer":"Wie lange arbeiten Sie schon hier?"},
    {"id":113,"software":[],"promptFa":"I have been working here for ten years.","expectedAnswer":"Ich arbeite hier seit zehn Jahren."},
    {"id":114,"software":[],"promptFa":"I have been waiting for you for ten minutes.","expectedAnswer":"Ich warte seit zehn Minuten auf Sie."},
    {"id":115,"software":[],"promptFa":"I will call you later because I am working now.","expectedAnswer":"Ich werde Sie später anrufen, weil ich jetzt arbeite."},
    {"id":116,"software":[],"promptFa":"I do not know whether I can come today, but I will try.","expectedAnswer":"Ich weiß nicht, ob ich heute kommen kann, aber ich werde versuchen."},
    {"id":117,"software":[],"promptFa":"I would like to know whether it will be ready today.","expectedAnswer":"Ich möchte wissen, ob es heute fertig sein wird."},
    {"id":118,"software":[],"promptFa":"I would like to know when it will be ready.","expectedAnswer":"Ich möchte wissen, wann es fertig sein wird."},
  ],
};
