// Lesson 4 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/lektion3.js - see main.js's
// INTERACTIVE_LESSONS map, which intercepts the "deutsch-almani-lektion-4"
// course card (a plain courses-table row, just for the level/title/grid-
// card metadata) and renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion4 = {
  id: 'lektion4',
  courseId: 'deutsch-almani-lektion-4',
  title: "Lektion 4 – Möchte, Gern, Wissen und Weil",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-4-v1',
  promptLang: 'en',
  // Formal register throughout (Sie/Ihnen).
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"möchten","persian":"would like"}],"promptFa":"I would like to do it.","expectedAnswer":"Ich möchte es tun."},
    {"id":2,"software":[],"promptFa":"I would like to see it.","expectedAnswer":"Ich möchte es sehen."},
    {"id":3,"software":[],"promptFa":"I would like to see you.","expectedAnswer":"Ich möchte Sie sehen."},
    {"id":4,"software":[],"promptFa":"I would like to have it.","expectedAnswer":"Ich möchte es haben."},
    {"id":5,"software":[],"promptFa":"I would like to go there.","expectedAnswer":"Ich möchte dorthin gehen."},
    {"id":6,"software":[],"promptFa":"I would like to stay here.","expectedAnswer":"Ich möchte hier bleiben."},
    {"id":7,"software":[],"promptFa":"I would like to do it today.","expectedAnswer":"Ich möchte es heute tun."},
    {"id":8,"software":[],"promptFa":"I would like to have it today.","expectedAnswer":"Ich möchte es heute haben."},
    {"id":9,"software":[{"german":"uns","persian":"us"}],"promptFa":"He would like to come with us.","expectedAnswer":"Er möchte mit uns kommen."},
    {"id":10,"software":[],"promptFa":"She would like to come with us.","expectedAnswer":"Sie möchte mit uns kommen."},
    {"id":11,"software":[],"promptFa":"Would you like to come with us?","expectedAnswer":"Möchten Sie mit uns kommen?"},
    {"id":12,"software":[],"promptFa":"We would like to go there with you.","expectedAnswer":"Wir möchten mit Ihnen dorthin gehen."},
    {"id":13,"software":[],"promptFa":"He can come with us.","expectedAnswer":"Er kann mit uns kommen."},
    {"id":14,"software":[],"promptFa":"She can come with us.","expectedAnswer":"Sie kann mit uns kommen."},
    {"id":15,"software":[],"promptFa":"Can he come with us?","expectedAnswer":"Kann er mit uns kommen?"},
    {"id":16,"software":[{"german":"möglich","persian":"possible"}],"promptFa":"It is possible.","expectedAnswer":"Es ist möglich."},
    {"id":17,"software":[],"promptFa":"It is not possible.","expectedAnswer":"Es ist nicht möglich."},
    {"id":18,"software":[],"promptFa":"Is it possible?","expectedAnswer":"Ist es möglich?"},
    {"id":19,"software":[],"promptFa":"Is it possible today?","expectedAnswer":"Ist es heute möglich?"},
    {"id":20,"software":[],"promptFa":"It is not possible today.","expectedAnswer":"Es ist heute nicht möglich."},
    {"id":21,"software":[],"promptFa":"It is not possible like this.","expectedAnswer":"So ist es nicht möglich."},
    {"id":22,"software":[{"german":"unmöglich","persian":"impossible"}],"promptFa":"It is impossible.","expectedAnswer":"Es ist unmöglich."},
    {"id":23,"software":[{"german":"ganz","persian":"completely"}],"promptFa":"It is completely impossible.","expectedAnswer":"Es ist ganz unmöglich."},
    {"id":24,"software":[],"promptFa":"Why is it impossible?","expectedAnswer":"Warum ist es unmöglich?"},
    {"id":25,"software":[],"promptFa":"Unfortunately, it is not possible today.","expectedAnswer":"Leider ist es heute nicht möglich."},
    {"id":26,"software":[{"german":"gern","persian":"gladly / like to"}],"promptFa":"I like doing it.","expectedAnswer":"Ich tue es gern."},
    {"id":27,"software":[],"promptFa":"I really like doing it.","expectedAnswer":"Ich tue es sehr gern."},
    {"id":28,"software":[],"promptFa":"I like seeing it.","expectedAnswer":"Ich sehe es gern."},
    {"id":29,"software":[],"promptFa":"I like going there.","expectedAnswer":"Ich gehe gern dorthin."},
    {"id":30,"software":[],"promptFa":"I like coming here.","expectedAnswer":"Ich komme gern hierher."},
    {"id":31,"software":[],"promptFa":"I like staying here.","expectedAnswer":"Ich bleibe gern hier."},
    {"id":32,"software":[],"promptFa":"I will gladly go there with you.","expectedAnswer":"Ich werde gern mit Ihnen dorthin gehen."},
    {"id":33,"software":[],"promptFa":"I will gladly come with you.","expectedAnswer":"Ich werde gern mit Ihnen kommen."},
    {"id":34,"software":[{"german":"sehr gern","persian":"with pleasure / very gladly"}],"promptFa":"Would you like to come with me?","expectedAnswer":"Möchten Sie mit mir kommen?"},
    {"id":35,"software":[],"promptFa":"Yes, with pleasure.","expectedAnswer":"Ja, sehr gern."},
    {"id":36,"software":[{"german":"danke","persian":"thank you"}],"promptFa":"Thank you.","expectedAnswer":"Danke."},
    {"id":37,"software":[{"german":"danke schön","persian":"thank you very much"}],"promptFa":"Thank you very much.","expectedAnswer":"Danke schön."},
    {"id":38,"software":[{"german":"besten Dank","persian":"many thanks"}],"promptFa":"Many thanks.","expectedAnswer":"Besten Dank."},
    {"id":39,"software":[{"german":"wissen","persian":"to know"}],"promptFa":"I know.","expectedAnswer":"Ich weiß."},
    {"id":40,"software":[],"promptFa":"Do you know?","expectedAnswer":"Wissen Sie?"},
    {"id":41,"software":[],"promptFa":"He knows.","expectedAnswer":"Er weiß."},
    {"id":42,"software":[],"promptFa":"I do not know.","expectedAnswer":"Ich weiß nicht."},
    {"id":43,"software":[],"promptFa":"I do not know where it is.","expectedAnswer":"Ich weiß nicht, wo es ist.","noteFa":"In an indirect question, the question word stays, but the conjugated verb moves to the end."},
    {"id":44,"software":[],"promptFa":"Do you know where it is?","expectedAnswer":"Wissen Sie, wo es ist?"},
    {"id":45,"software":[],"promptFa":"Can you tell me where it is?","expectedAnswer":"Können Sie mir sagen, wo es ist?"},
    {"id":46,"software":[],"promptFa":"Would you tell me where it is?","expectedAnswer":"Möchten Sie mir sagen, wo es ist?"},
    {"id":47,"software":[],"promptFa":"I do not know where it is because I cannot find it.","expectedAnswer":"Ich weiß nicht, wo es ist, denn ich kann es nicht finden."},
    {"id":48,"software":[],"promptFa":"I cannot find it. Can you tell me where it is?","expectedAnswer":"Ich kann es nicht finden. Können Sie mir sagen, wo es ist?"},
    {"id":49,"software":[{"german":"müde","persian":"tired"}],"promptFa":"I am tired.","expectedAnswer":"Ich bin müde."},
    {"id":50,"software":[],"promptFa":"I am very tired.","expectedAnswer":"Ich bin sehr müde."},
    {"id":51,"software":[],"promptFa":"Are you tired?","expectedAnswer":"Sind Sie müde?"},
    {"id":52,"software":[],"promptFa":"I am very tired today.","expectedAnswer":"Ich bin heute sehr müde."},
    {"id":53,"software":[{"german":"das Haus","persian":"house"},{"german":"zu Hause","persian":"at home"},{"german":"nach Hause","persian":"home, toward home"}],"promptFa":"I am at home.","expectedAnswer":"Ich bin zu Hause.","noteFa":"Use \"zu Hause\" for location and \"nach Hause\" for movement toward home."},
    {"id":54,"software":[],"promptFa":"I am going home.","expectedAnswer":"Ich gehe nach Hause."},
    {"id":55,"software":[],"promptFa":"I am going home now.","expectedAnswer":"Ich gehe jetzt nach Hause."},
    {"id":56,"software":[],"promptFa":"I am staying at home.","expectedAnswer":"Ich bleibe zu Hause."},
    {"id":57,"software":[],"promptFa":"I will stay at home.","expectedAnswer":"Ich werde zu Hause bleiben."},
    {"id":58,"software":[],"promptFa":"I will stay at home this evening.","expectedAnswer":"Ich werde heute Abend zu Hause bleiben."},
    {"id":59,"software":[],"promptFa":"I am very tired and I am going home now.","expectedAnswer":"Ich bin sehr müde und ich gehe jetzt nach Hause."},
    {"id":60,"software":[],"promptFa":"I am very tired, so I will stay at home this evening.","expectedAnswer":"Ich bin sehr müde, deshalb werde ich heute Abend zu Hause bleiben."},
    {"id":61,"software":[],"promptFa":"I will stay at home this evening because I am very tired.","expectedAnswer":"Ich werde heute Abend zu Hause bleiben, denn ich bin sehr müde."},
    {"id":62,"software":[{"german":"weil","persian":"because"}],"promptFa":"because I am very tired","expectedAnswer":"weil ich sehr müde bin","noteFa":"\"weil\" introduces a subordinate clause, so the conjugated verb goes to the end."},
    {"id":63,"software":[],"promptFa":"I will stay at home because I am very tired.","expectedAnswer":"Ich werde zu Hause bleiben, weil ich sehr müde bin."},
    {"id":64,"software":[],"promptFa":"I am going home because I am tired.","expectedAnswer":"Ich gehe nach Hause, weil ich müde bin."},
    {"id":65,"software":[],"promptFa":"I cannot go there today because I am very busy.","expectedAnswer":"Ich kann heute nicht dorthin gehen, weil ich sehr beschäftigt bin."},
    {"id":66,"software":[],"promptFa":"I cannot do it because I am very busy today.","expectedAnswer":"Ich kann es nicht tun, weil ich heute sehr beschäftigt bin."},
    {"id":67,"software":[],"promptFa":"I cannot come with you this evening because I am very busy.","expectedAnswer":"Ich kann heute Abend nicht mit Ihnen kommen, weil ich sehr beschäftigt bin."},
    {"id":68,"software":[],"promptFa":"I do not understand you.","expectedAnswer":"Ich verstehe Sie nicht."},
    {"id":69,"software":[],"promptFa":"I cannot understand you.","expectedAnswer":"Ich kann Sie nicht verstehen."},
    {"id":70,"software":[],"promptFa":"I do not know what you are saying.","expectedAnswer":"Ich weiß nicht, was Sie sagen."},
    {"id":71,"software":[],"promptFa":"Can you tell me what you are saying?","expectedAnswer":"Können Sie mir sagen, was Sie sagen?"},
    {"id":72,"software":[],"promptFa":"I do not know what you are saying because I do not understand you.","expectedAnswer":"Ich weiß nicht, was Sie sagen, weil ich Sie nicht verstehe."},
    {"id":73,"software":[],"promptFa":"I do not know what you are saying because I cannot understand you.","expectedAnswer":"Ich weiß nicht, was Sie sagen, weil ich Sie nicht verstehen kann."},
    {"id":74,"software":[],"promptFa":"because I cannot understand you","expectedAnswer":"weil ich Sie nicht verstehen kann"},
    {"id":75,"software":[],"promptFa":"I cannot do it because I will be very busy.","expectedAnswer":"Ich kann es nicht tun, weil ich sehr beschäftigt sein werde."},
    {"id":76,"software":[],"promptFa":"because I cannot come with you this evening","expectedAnswer":"weil ich heute Abend nicht mit Ihnen kommen kann"},
    {"id":77,"software":[],"promptFa":"I cannot tell you.","expectedAnswer":"Ich kann Ihnen nicht sagen."},
    {"id":78,"software":[],"promptFa":"I cannot tell you that.","expectedAnswer":"Ich kann es Ihnen nicht sagen."},
    {"id":79,"software":[],"promptFa":"I cannot tell you that now.","expectedAnswer":"Ich kann es Ihnen jetzt nicht sagen."},
    {"id":80,"software":[],"promptFa":"because I do not know it","expectedAnswer":"weil ich es nicht weiß"},
    {"id":81,"software":[],"promptFa":"I cannot tell you that now because I do not know it.","expectedAnswer":"Ich kann es Ihnen jetzt nicht sagen, weil ich es nicht weiß."},
    {"id":82,"software":[{"german":"kosten","persian":"to cost"}],"promptFa":"It costs.","expectedAnswer":"Es kostet."},
    {"id":83,"software":[{"german":"wie viel","persian":"how much"}],"promptFa":"How much does it cost?","expectedAnswer":"Wie viel kostet es?"},
    {"id":84,"software":[],"promptFa":"I want to know how much it costs.","expectedAnswer":"Ich will wissen, wie viel es kostet."},
    {"id":85,"software":[],"promptFa":"I would like to know how much it costs.","expectedAnswer":"Ich möchte wissen, wie viel es kostet."},
    {"id":86,"software":[],"promptFa":"Can you tell me how much it costs?","expectedAnswer":"Können Sie mir sagen, wie viel es kostet?"},
    {"id":87,"software":[],"promptFa":"Do you know how much it costs?","expectedAnswer":"Wissen Sie, wie viel es kostet?"},
    {"id":88,"software":[],"promptFa":"I do not know how much it costs.","expectedAnswer":"Ich weiß nicht, wie viel es kostet."},
    {"id":89,"software":[],"promptFa":"I need it.","expectedAnswer":"Ich brauche es."},
    {"id":90,"software":[],"promptFa":"because I need it","expectedAnswer":"weil ich es brauche"},
    {"id":91,"software":[],"promptFa":"I would like to have it because I need it.","expectedAnswer":"Ich möchte es haben, weil ich es brauche."},
    {"id":92,"software":[],"promptFa":"because I want to have it","expectedAnswer":"weil ich es haben will"},
    {"id":93,"software":[],"promptFa":"I will buy it because I want to have it.","expectedAnswer":"Ich werde es kaufen, weil ich es haben will."},
    {"id":94,"software":[],"promptFa":"because I must have it","expectedAnswer":"weil ich es haben muss"},
    {"id":95,"software":[],"promptFa":"I need it today because I must have it today.","expectedAnswer":"Ich brauche es heute, weil ich es heute haben muss."},
    {"id":96,"software":[],"promptFa":"When can I have it?","expectedAnswer":"Wann kann ich es haben?"},
    {"id":97,"software":[],"promptFa":"At what time can I have it?","expectedAnswer":"Um wie viel Uhr kann ich es haben?"},
    {"id":98,"software":[],"promptFa":"I want to know at what time I can have it.","expectedAnswer":"Ich will wissen, um wie viel Uhr ich es haben kann."},
    {"id":99,"software":[],"promptFa":"I would like to know at what time I can have it.","expectedAnswer":"Ich möchte wissen, um wie viel Uhr ich es haben kann."},
    {"id":100,"software":[],"promptFa":"Can you tell me at what time I can have it?","expectedAnswer":"Können Sie mir sagen, um wie viel Uhr ich es haben kann?"},
    {"id":101,"software":[],"promptFa":"I want to know when I can have it.","expectedAnswer":"Ich will wissen, wann ich es haben kann."},
    {"id":102,"software":[],"promptFa":"I would like to know when I can have it.","expectedAnswer":"Ich möchte wissen, wann ich es haben kann."},
    {"id":103,"software":[],"promptFa":"Can you tell me when I can have it?","expectedAnswer":"Können Sie mir sagen, wann ich es haben kann?"},
    {"id":104,"software":[],"promptFa":"Would you tell me when I can have it?","expectedAnswer":"Möchten Sie mir sagen, wann ich es haben kann?"},
    {"id":105,"software":[],"promptFa":"I would like to know when you can bring it to me.","expectedAnswer":"Ich möchte wissen, wann Sie es mir bringen können."},
    {"id":106,"software":[],"promptFa":"Can you tell me when you can bring it to me?","expectedAnswer":"Können Sie mir sagen, wann Sie es mir bringen können?"},
    {"id":107,"software":[],"promptFa":"Why do I have to do it today?","expectedAnswer":"Warum muss ich es heute machen?"},
    {"id":108,"software":[],"promptFa":"I do not know why I have to do it today.","expectedAnswer":"Ich weiß nicht, warum ich es heute machen muss."},
    {"id":109,"software":[],"promptFa":"I cannot tell you why I have to do it today.","expectedAnswer":"Ich kann Ihnen nicht sagen, warum ich es heute machen muss."},
    {"id":110,"software":[],"promptFa":"I cannot tell you now why I have to do it today.","expectedAnswer":"Ich kann Ihnen jetzt nicht sagen, warum ich es heute machen muss."},
    {"id":111,"software":[],"promptFa":"I am sorry, but I cannot tell you now why I have to do it today.","expectedAnswer":"Es tut mir leid, aber ich kann Ihnen jetzt nicht sagen, warum ich es heute machen muss."},
    {"id":112,"software":[],"promptFa":"Why do I have to have it today?","expectedAnswer":"Warum muss ich es heute haben?"},
    {"id":113,"software":[],"promptFa":"I do not know why I have to have it today.","expectedAnswer":"Ich weiß nicht, warum ich es heute haben muss."},
    {"id":114,"software":[],"promptFa":"Can you tell me why I have to have it today?","expectedAnswer":"Können Sie mir sagen, warum ich es heute haben muss?"},
    {"id":115,"software":[],"promptFa":"I would like to go home because I am very tired.","expectedAnswer":"Ich möchte nach Hause gehen, weil ich sehr müde bin."},
    {"id":116,"software":[],"promptFa":"I would like to stay at home this evening because I am tired.","expectedAnswer":"Ich möchte heute Abend zu Hause bleiben, weil ich müde bin."},
    {"id":117,"software":[],"promptFa":"I would like to know where it is.","expectedAnswer":"Ich möchte wissen, wo es ist."},
    {"id":118,"software":[],"promptFa":"I would like to know what you are saying.","expectedAnswer":"Ich möchte wissen, was Sie sagen."},
    {"id":119,"software":[],"promptFa":"I would like to know how much it costs.","expectedAnswer":"Ich möchte wissen, wie viel es kostet."},
    {"id":120,"software":[],"promptFa":"I would like to know when I can have it.","expectedAnswer":"Ich möchte wissen, wann ich es haben kann."},
    {"id":121,"software":[],"promptFa":"I would like to know why it is not possible.","expectedAnswer":"Ich möchte wissen, warum es nicht möglich ist."},
    {"id":122,"software":[],"promptFa":"I do not know where it is.","expectedAnswer":"Ich weiß nicht, wo es ist."},
    {"id":123,"software":[],"promptFa":"I do not know what you are saying.","expectedAnswer":"Ich weiß nicht, was Sie sagen."},
    {"id":124,"software":[],"promptFa":"I do not know how much it costs.","expectedAnswer":"Ich weiß nicht, wie viel es kostet."},
    {"id":125,"software":[],"promptFa":"I do not know when I can have it.","expectedAnswer":"Ich weiß nicht, wann ich es haben kann."},
    {"id":126,"software":[],"promptFa":"I do not know why I need it.","expectedAnswer":"Ich weiß nicht, warum ich es brauche."},
    {"id":127,"software":[],"promptFa":"Can you tell me where it is?","expectedAnswer":"Können Sie mir sagen, wo es ist?"},
    {"id":128,"software":[],"promptFa":"Can you tell me how much it costs?","expectedAnswer":"Können Sie mir sagen, wie viel es kostet?"},
    {"id":129,"software":[],"promptFa":"Can you tell me when I can have it?","expectedAnswer":"Können Sie mir sagen, wann ich es haben kann?"},
    {"id":130,"software":[],"promptFa":"Can you tell me why it is not possible?","expectedAnswer":"Können Sie mir sagen, warum es nicht möglich ist?"},
    {"id":131,"software":[],"promptFa":"I am very tired, so I would like to go home.","expectedAnswer":"Ich bin sehr müde, deshalb möchte ich nach Hause gehen."},
    {"id":132,"software":[],"promptFa":"I will stay at home because I am very tired.","expectedAnswer":"Ich werde zu Hause bleiben, weil ich sehr müde bin."},
    {"id":133,"software":[],"promptFa":"I would like to know where it is because I cannot find it.","expectedAnswer":"Ich möchte wissen, wo es ist, weil ich es nicht finden kann."},
    {"id":134,"software":[],"promptFa":"I would like to have it because I need it.","expectedAnswer":"Ich möchte es haben, weil ich es brauche."},
    {"id":135,"software":[],"promptFa":"I cannot tell you now because I do not know it.","expectedAnswer":"Ich kann es Ihnen jetzt nicht sagen, weil ich es nicht weiß."},
    {"id":136,"software":[],"promptFa":"I do not know what you are saying because I cannot understand you.","expectedAnswer":"Ich weiß nicht, was Sie sagen, weil ich Sie nicht verstehen kann."},
  ],
};
