// Lesson 7 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/.../lektion6.js - see main.js's
// INTERACTIVE_LESSONS map, which intercepts the "deutsch-almani-lektion-7"
// course card (a plain courses-table row, just for the level/title/grid-
// card metadata) and renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion7 = {
  id: 'lektion7',
  courseId: 'deutsch-almani-lektion-7',
  title: "Lektion 7 – Vergangenheit, Könnten, Dürfen und Lassen",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-7-v1',
  promptLang: 'en',
  // Formal register throughout (Sie/Ihnen).
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"konnte","persian":"could / was able to"}],"promptFa":"I could do it.","expectedAnswer":"Ich konnte es tun."},
    {"id":2,"software":[],"promptFa":"I could not do it.","expectedAnswer":"Ich konnte es nicht tun."},
    {"id":3,"software":[],"promptFa":"I could not find it.","expectedAnswer":"Ich konnte es nicht finden."},
    {"id":4,"software":[],"promptFa":"I could not understand you.","expectedAnswer":"Ich konnte Sie nicht verstehen."},
    {"id":5,"software":[{"german":"gestern","persian":"yesterday"}],"promptFa":"I could not find it yesterday.","expectedAnswer":"Ich konnte es gestern nicht finden."},
    {"id":6,"software":[],"promptFa":"I could not do it yesterday.","expectedAnswer":"Ich konnte es gestern nicht tun."},
    {"id":7,"software":[],"promptFa":"I could not come yesterday.","expectedAnswer":"Ich konnte gestern nicht kommen."},
    {"id":8,"software":[],"promptFa":"I could not go there yesterday.","expectedAnswer":"Ich konnte gestern nicht dorthin gehen."},
    {"id":9,"software":[{"german":"konnten","persian":"could / were able to"}],"promptFa":"We could do it.","expectedAnswer":"Wir konnten es tun."},
    {"id":10,"software":[],"promptFa":"We could not do it.","expectedAnswer":"Wir konnten es nicht tun."},
    {"id":11,"software":[],"promptFa":"Could you do it?","expectedAnswer":"Konnten Sie es tun?"},
    {"id":12,"software":[],"promptFa":"Could you find it?","expectedAnswer":"Konnten Sie es finden?"},
    {"id":13,"software":[],"promptFa":"We could not go there yesterday evening.","expectedAnswer":"Wir konnten gestern Abend nicht dorthin gehen."},
    {"id":14,"software":[],"promptFa":"He could not go there with us yesterday evening.","expectedAnswer":"Er konnte gestern Abend nicht mit uns dorthin gehen."},
    {"id":15,"software":[{"german":"war","persian":"was"}],"promptFa":"I was there.","expectedAnswer":"Ich war da."},
    {"id":16,"software":[],"promptFa":"I was there yesterday.","expectedAnswer":"Ich war gestern da."},
    {"id":17,"software":[],"promptFa":"I was there yesterday evening.","expectedAnswer":"Ich war gestern Abend da."},
    {"id":18,"software":[],"promptFa":"He was here yesterday.","expectedAnswer":"Er war gestern hier."},
    {"id":19,"software":[],"promptFa":"It was ready.","expectedAnswer":"Es war fertig."},
    {"id":20,"software":[],"promptFa":"It was not ready.","expectedAnswer":"Es war nicht fertig."},
    {"id":21,"software":[],"promptFa":"It was not possible.","expectedAnswer":"Es war nicht möglich."},
    {"id":22,"software":[],"promptFa":"It was not possible to do it.","expectedAnswer":"Es war nicht möglich, es zu tun."},
    {"id":23,"software":[{"german":"waren","persian":"were"}],"promptFa":"We were there.","expectedAnswer":"Wir waren da."},
    {"id":24,"software":[],"promptFa":"We were there yesterday.","expectedAnswer":"Wir waren gestern da."},
    {"id":25,"software":[],"promptFa":"Where were you?","expectedAnswer":"Wo waren Sie?"},
    {"id":26,"software":[],"promptFa":"Where were you yesterday evening?","expectedAnswer":"Wo waren Sie gestern Abend?"},
    {"id":27,"software":[],"promptFa":"We were very busy yesterday.","expectedAnswer":"Wir waren gestern sehr beschäftigt."},
    {"id":28,"software":[{"german":"hatte","persian":"had"}],"promptFa":"I had time.","expectedAnswer":"Ich hatte Zeit."},
    {"id":29,"software":[],"promptFa":"I had no time.","expectedAnswer":"Ich hatte keine Zeit."},
    {"id":30,"software":[],"promptFa":"I had no time yesterday.","expectedAnswer":"Ich hatte gestern keine Zeit."},
    {"id":31,"software":[],"promptFa":"I had no time to do it.","expectedAnswer":"Ich hatte keine Zeit, es zu tun."},
    {"id":32,"software":[],"promptFa":"I had no time to do it because I was very busy.","expectedAnswer":"Ich hatte keine Zeit, es zu tun, weil ich sehr beschäftigt war."},
    {"id":33,"software":[{"german":"hatten","persian":"had, plural/formal"}],"promptFa":"We had time.","expectedAnswer":"Wir hatten Zeit."},
    {"id":34,"software":[],"promptFa":"We had no time.","expectedAnswer":"Wir hatten keine Zeit."},
    {"id":35,"software":[],"promptFa":"Did you have time?","expectedAnswer":"Hatten Sie Zeit?"},
    {"id":36,"software":[],"promptFa":"Did you have time yesterday?","expectedAnswer":"Hatten Sie gestern Zeit?"},
    {"id":37,"software":[],"promptFa":"We had no time because we were very busy.","expectedAnswer":"Wir hatten keine Zeit, weil wir sehr beschäftigt waren."},
    {"id":38,"software":[{"german":"könnten","persian":"could / could you, polite or hypothetical"}],"promptFa":"Could you come with me?","expectedAnswer":"Könnten Sie mit mir kommen?","noteFa":"\"Könnten Sie...?\" is a more polite form than \"Können Sie...?\""},
    {"id":39,"software":[],"promptFa":"Could you tell me?","expectedAnswer":"Könnten Sie mir sagen?"},
    {"id":40,"software":[],"promptFa":"Could you tell me where it is?","expectedAnswer":"Könnten Sie mir sagen, wo es ist?"},
    {"id":41,"software":[],"promptFa":"Could you wait here?","expectedAnswer":"Könnten Sie hier warten?"},
    {"id":42,"software":[],"promptFa":"Could you wait for me?","expectedAnswer":"Könnten Sie auf mich warten?"},
    {"id":43,"software":[],"promptFa":"Could you call me later?","expectedAnswer":"Könnten Sie mich später anrufen?"},
    {"id":44,"software":[{"german":"ohne","persian":"without"}],"promptFa":"I cannot do it without you.","expectedAnswer":"Ich kann es ohne Sie nicht tun."},
    {"id":45,"software":[],"promptFa":"I could not do it without you yesterday.","expectedAnswer":"Ich konnte es gestern ohne Sie nicht tun."},
    {"id":46,"software":[],"promptFa":"I cannot go there without you.","expectedAnswer":"Ich kann ohne Sie nicht dorthin gehen."},
    {"id":47,"software":[],"promptFa":"I do not want to do it without you.","expectedAnswer":"Ich will es ohne Sie nicht tun."},
    {"id":48,"software":[],"promptFa":"We could not do it without you.","expectedAnswer":"Wir konnten es ohne Sie nicht tun."},
    {"id":49,"software":[{"german":"musste","persian":"had to"}],"promptFa":"I had to go.","expectedAnswer":"Ich musste gehen."},
    {"id":50,"software":[],"promptFa":"I had to go yesterday.","expectedAnswer":"Ich musste gestern gehen."},
    {"id":51,"software":[],"promptFa":"I had to stay here.","expectedAnswer":"Ich musste hier bleiben."},
    {"id":52,"software":[],"promptFa":"I had to wait.","expectedAnswer":"Ich musste warten."},
    {"id":53,"software":[],"promptFa":"He had to wait for me.","expectedAnswer":"Er musste auf mich warten."},
    {"id":54,"software":[],"promptFa":"He had to stay here because he had to work.","expectedAnswer":"Er musste hier bleiben, weil er arbeiten musste."},
    {"id":55,"software":[{"german":"mussten","persian":"had to, plural/formal"}],"promptFa":"We had to wait.","expectedAnswer":"Wir mussten warten."},
    {"id":56,"software":[],"promptFa":"We had to buy it.","expectedAnswer":"Wir mussten es kaufen."},
    {"id":57,"software":[],"promptFa":"Did you have to stay here?","expectedAnswer":"Mussten Sie hier bleiben?"},
    {"id":58,"software":[],"promptFa":"Did you have to wait for me?","expectedAnswer":"Mussten Sie auf mich warten?"},
    {"id":59,"software":[],"promptFa":"We had to stay here because we had no time.","expectedAnswer":"Wir mussten hier bleiben, weil wir keine Zeit hatten."},
    {"id":60,"software":[{"german":"wollte","persian":"wanted to"}],"promptFa":"I wanted to do it.","expectedAnswer":"Ich wollte es tun."},
    {"id":61,"software":[],"promptFa":"I wanted to buy it.","expectedAnswer":"Ich wollte es kaufen."},
    {"id":62,"software":[],"promptFa":"I wanted to have it.","expectedAnswer":"Ich wollte es haben."},
    {"id":63,"software":[],"promptFa":"I did not want to stay here.","expectedAnswer":"Ich wollte hier nicht bleiben."},
    {"id":64,"software":[],"promptFa":"He wanted to buy it.","expectedAnswer":"Er wollte es kaufen."},
    {"id":65,"software":[],"promptFa":"He wanted to buy it because he wanted to have it.","expectedAnswer":"Er wollte es kaufen, weil er es haben wollte."},
    {"id":66,"software":[{"german":"wollten","persian":"wanted to, plural/formal"}],"promptFa":"We wanted to do it.","expectedAnswer":"Wir wollten es tun."},
    {"id":67,"software":[],"promptFa":"We did not want to do it.","expectedAnswer":"Wir wollten es nicht tun."},
    {"id":68,"software":[],"promptFa":"We did not want to stay here.","expectedAnswer":"Wir wollten hier nicht bleiben."},
    {"id":69,"software":[],"promptFa":"Did you want to buy it?","expectedAnswer":"Wollten Sie es kaufen?"},
    {"id":70,"software":[],"promptFa":"Why did you not want to do it?","expectedAnswer":"Warum wollten Sie es nicht tun?"},
    {"id":71,"software":[],"promptFa":"We wanted to go there, but we could not go.","expectedAnswer":"Wir wollten dorthin gehen, aber wir konnten nicht gehen."},
    {"id":72,"software":[{"german":"soll","persian":"should / is supposed to"}],"promptFa":"I should do it.","expectedAnswer":"Ich soll es tun."},
    {"id":73,"software":[],"promptFa":"He should wait.","expectedAnswer":"Er soll warten."},
    {"id":74,"software":[],"promptFa":"He should wait for me.","expectedAnswer":"Er soll auf mich warten."},
    {"id":75,"software":[],"promptFa":"It should be ready.","expectedAnswer":"Es soll fertig sein."},
    {"id":76,"software":[],"promptFa":"What should I do?","expectedAnswer":"Was soll ich tun?"},
    {"id":77,"software":[{"german":"sollten","persian":"should / were supposed to"}],"promptFa":"We should stay here.","expectedAnswer":"Wir sollten hier bleiben."},
    {"id":78,"software":[],"promptFa":"You should tell me.","expectedAnswer":"Sie sollten mir sagen."},
    {"id":79,"software":[],"promptFa":"You should wait here.","expectedAnswer":"Sie sollten hier warten."},
    {"id":80,"software":[],"promptFa":"You should call me later.","expectedAnswer":"Sie sollten mich später anrufen."},
    {"id":81,"software":[{"german":"sollte","persian":"should / was supposed to"}],"promptFa":"He should wait for me.","expectedAnswer":"Er sollte auf mich warten."},
    {"id":82,"software":[],"promptFa":"He was supposed to wait for me.","expectedAnswer":"Er sollte auf mich warten."},
    {"id":83,"software":[],"promptFa":"I was supposed to do it yesterday.","expectedAnswer":"Ich sollte es gestern tun."},
    {"id":84,"software":[],"promptFa":"It was supposed to be ready yesterday.","expectedAnswer":"Es sollte gestern fertig sein."},
    {"id":85,"software":[],"promptFa":"He was supposed to wait, but he could not wait.","expectedAnswer":"Er sollte warten, aber er konnte nicht warten."},
    {"id":86,"software":[{"german":"dürfen","persian":"to be allowed to / may"}],"promptFa":"We are allowed to do it.","expectedAnswer":"Wir dürfen es tun."},
    {"id":87,"software":[],"promptFa":"Are you allowed to do it?","expectedAnswer":"Dürfen Sie es tun?"},
    {"id":88,"software":[],"promptFa":"Are you allowed to go there?","expectedAnswer":"Dürfen Sie dorthin gehen?"},
    {"id":89,"software":[],"promptFa":"We are not allowed to do it.","expectedAnswer":"Wir dürfen es nicht tun."},
    {"id":90,"software":[{"german":"darf","persian":"may / am allowed to"}],"promptFa":"I am allowed to do it.","expectedAnswer":"Ich darf es tun."},
    {"id":91,"software":[],"promptFa":"May I see it?","expectedAnswer":"Darf ich es sehen?"},
    {"id":92,"software":[],"promptFa":"May I come in?","expectedAnswer":"Darf ich hereinkommen?"},
    {"id":93,"software":[],"promptFa":"May I ask you?","expectedAnswer":"Darf ich Sie fragen?"},
    {"id":94,"software":[],"promptFa":"One is not allowed to do that.","expectedAnswer":"Man darf das nicht tun."},
    {"id":95,"software":[{"german":"anprobieren","persian":"to try on"}],"promptFa":"May I try it on?","expectedAnswer":"Darf ich es anprobieren?"},
    {"id":96,"software":[],"promptFa":"I would like to try it on.","expectedAnswer":"Ich möchte es anprobieren."},
    {"id":97,"software":[],"promptFa":"Can I try it on?","expectedAnswer":"Kann ich es anprobieren?"},
    {"id":98,"software":[],"promptFa":"May I try it on here?","expectedAnswer":"Darf ich es hier anprobieren?"},
    {"id":99,"software":[{"german":"Lust","persian":"desire / desire to do something"}],"promptFa":"I have no desire.","expectedAnswer":"Ich habe keine Lust."},
    {"id":100,"software":[],"promptFa":"I have no desire to do it.","expectedAnswer":"Ich habe keine Lust, es zu tun."},
    {"id":101,"software":[],"promptFa":"I have no desire to go there.","expectedAnswer":"Ich habe keine Lust, dorthin zu gehen."},
    {"id":102,"software":[],"promptFa":"I have no desire to wait.","expectedAnswer":"Ich habe keine Lust zu warten."},
    {"id":103,"software":[],"promptFa":"I wanted to do it, but now I have no desire.","expectedAnswer":"Ich wollte es tun, aber jetzt habe ich keine Lust."},
    {"id":104,"software":[{"german":"wäre","persian":"would be"}],"promptFa":"It would be possible.","expectedAnswer":"Es wäre möglich.","noteFa":"\"wäre\" is the hypothetical form of \"sein\" for ich/er/sie/es."},
    {"id":105,"software":[],"promptFa":"It would not be possible.","expectedAnswer":"Es wäre nicht möglich."},
    {"id":106,"software":[],"promptFa":"It would be good.","expectedAnswer":"Es wäre gut."},
    {"id":107,"software":[],"promptFa":"It would be very good.","expectedAnswer":"Es wäre sehr gut."},
    {"id":108,"software":[],"promptFa":"It would be possible to do it today.","expectedAnswer":"Es wäre möglich, es heute zu tun."},
    {"id":109,"software":[{"german":"wären","persian":"would be, plural/formal"}],"promptFa":"We would be here.","expectedAnswer":"Wir wären hier."},
    {"id":110,"software":[],"promptFa":"We would be ready.","expectedAnswer":"Wir wären fertig."},
    {"id":111,"software":[],"promptFa":"Would you be here tomorrow?","expectedAnswer":"Wären Sie morgen hier?"},
    {"id":112,"software":[],"promptFa":"Would you be ready tomorrow?","expectedAnswer":"Wären Sie morgen fertig?"},
    {"id":113,"software":[],"promptFa":"It would be good if you were here.","expectedAnswer":"Es wäre gut, wenn Sie hier wären."},
    {"id":114,"software":[{"german":"lassen","persian":"to let / to have something done"}],"promptFa":"I will have it repaired.","expectedAnswer":"Ich werde es reparieren lassen."},
    {"id":115,"software":[{"german":"reparieren","persian":"to repair"}],"promptFa":"I will repair it.","expectedAnswer":"Ich werde es reparieren."},
    {"id":116,"software":[],"promptFa":"I have to repair it.","expectedAnswer":"Ich muss es reparieren."},
    {"id":117,"software":[],"promptFa":"Do you want to repair it?","expectedAnswer":"Wollen Sie es reparieren?"},
    {"id":118,"software":[],"promptFa":"I will have it repaired.","expectedAnswer":"Ich werde es reparieren lassen."},
    {"id":119,"software":[],"promptFa":"I have to have it repaired.","expectedAnswer":"Ich muss es reparieren lassen."},
    {"id":120,"software":[],"promptFa":"Do you want to have it repaired?","expectedAnswer":"Wollen Sie es reparieren lassen?"},
    {"id":121,"software":[],"promptFa":"I would like to have it repaired.","expectedAnswer":"Ich möchte es reparieren lassen."},
    {"id":122,"software":[{"german":"rein","persian":"clean / pure"},{"german":"sauber","persian":"clean"}],"promptFa":"It is clean.","expectedAnswer":"Es ist sauber."},
    {"id":123,"software":[],"promptFa":"It is very clean.","expectedAnswer":"Es ist sehr sauber."},
    {"id":124,"software":[{"german":"reinigen","persian":"to clean"}],"promptFa":"I will clean it.","expectedAnswer":"Ich werde es reinigen."},
    {"id":125,"software":[],"promptFa":"I have to clean it.","expectedAnswer":"Ich muss es reinigen."},
    {"id":126,"software":[],"promptFa":"Do you want to clean it?","expectedAnswer":"Wollen Sie es reinigen?"},
    {"id":127,"software":[],"promptFa":"I will have it cleaned.","expectedAnswer":"Ich werde es reinigen lassen."},
    {"id":128,"software":[],"promptFa":"I have to have it cleaned.","expectedAnswer":"Ich muss es reinigen lassen."},
    {"id":129,"software":[],"promptFa":"Do you want to have it cleaned?","expectedAnswer":"Wollen Sie es reinigen lassen?"},
    {"id":130,"software":[],"promptFa":"I would like to have it cleaned.","expectedAnswer":"Ich möchte es reinigen lassen."},
    {"id":131,"software":[],"promptFa":"I could not do it yesterday because I had no time.","expectedAnswer":"Ich konnte es gestern nicht tun, weil ich keine Zeit hatte."},
    {"id":132,"software":[],"promptFa":"We could not go there because we were very busy.","expectedAnswer":"Wir konnten nicht dorthin gehen, weil wir sehr beschäftigt waren."},
    {"id":133,"software":[],"promptFa":"I wanted to buy it, but it was too expensive.","expectedAnswer":"Ich wollte es kaufen, aber es war zu teuer."},
    {"id":134,"software":[],"promptFa":"He wanted to buy it, but he could not buy it.","expectedAnswer":"Er wollte es kaufen, aber er konnte es nicht kaufen."},
    {"id":135,"software":[],"promptFa":"He could not buy it because it was too expensive.","expectedAnswer":"Er konnte es nicht kaufen, weil es zu teuer war."},
    {"id":136,"software":[],"promptFa":"I had to stay here because I had work.","expectedAnswer":"Ich musste hier bleiben, weil ich Arbeit hatte."},
    {"id":137,"software":[],"promptFa":"We had to wait because it was not ready.","expectedAnswer":"Wir mussten warten, weil es nicht fertig war."},
    {"id":138,"software":[],"promptFa":"Could you tell me why it was not ready?","expectedAnswer":"Könnten Sie mir sagen, warum es nicht fertig war?"},
    {"id":139,"software":[],"promptFa":"Could you tell me where you were yesterday?","expectedAnswer":"Könnten Sie mir sagen, wo Sie gestern waren?"},
    {"id":140,"software":[],"promptFa":"Could you wait for me here?","expectedAnswer":"Könnten Sie hier auf mich warten?"},
    {"id":141,"software":[],"promptFa":"May I try it on?","expectedAnswer":"Darf ich es anprobieren?"},
    {"id":142,"software":[],"promptFa":"I have no desire to buy it because it is too expensive.","expectedAnswer":"Ich habe keine Lust, es zu kaufen, weil es zu teuer ist."},
    {"id":143,"software":[],"promptFa":"It would be good to have it repaired.","expectedAnswer":"Es wäre gut, es reparieren zu lassen."},
    {"id":144,"software":[],"promptFa":"It would be good to have it cleaned.","expectedAnswer":"Es wäre gut, es reinigen zu lassen."},
    {"id":145,"software":[],"promptFa":"I wanted to do it yesterday, but I had no time.","expectedAnswer":"Ich wollte es gestern tun, aber ich hatte keine Zeit."},
    {"id":146,"software":[],"promptFa":"I had no time because I had to work.","expectedAnswer":"Ich hatte keine Zeit, weil ich arbeiten musste."},
    {"id":147,"software":[],"promptFa":"We wanted to go there, but we had to stay here.","expectedAnswer":"Wir wollten dorthin gehen, aber wir mussten hier bleiben."},
    {"id":148,"software":[],"promptFa":"He was supposed to wait for me, but he could not wait.","expectedAnswer":"Er sollte auf mich warten, aber er konnte nicht warten."},
    {"id":149,"software":[],"promptFa":"Would it be possible to do it tomorrow?","expectedAnswer":"Wäre es möglich, es morgen zu tun?"},
    {"id":150,"software":[],"promptFa":"Would you be here tomorrow?","expectedAnswer":"Wären Sie morgen hier?"},
    {"id":151,"software":[],"promptFa":"Could you repair it?","expectedAnswer":"Könnten Sie es reparieren?"},
    {"id":152,"software":[],"promptFa":"Could you have it repaired?","expectedAnswer":"Könnten Sie es reparieren lassen?"},
  ],
};
