// Lesson 5 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/lektion3.js/lektion4.js - see main.js's
// INTERACTIVE_LESSONS map, which intercepts the "deutsch-almani-lektion-5"
// course card (a plain courses-table row, just for the level/title/grid-
// card metadata) and renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion5 = {
  id: 'lektion5',
  courseId: 'deutsch-almani-lektion-5',
  title: "Lektion 5 – Fragen, Reflexive Verben, Interesse und zu + Infinitiv",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-5-v1',
  promptLang: 'en',
  // Formal register throughout (Sie/Ihnen).
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"fragen","persian":"to ask"}],"promptFa":"I ask.","expectedAnswer":"Ich frage."},
    {"id":2,"software":[{"german":"die Frage","persian":"question"}],"promptFa":"I have a question.","expectedAnswer":"Ich habe eine Frage."},
    {"id":3,"software":[],"promptFa":"Do you have a question?","expectedAnswer":"Haben Sie eine Frage?"},
    {"id":4,"software":[],"promptFa":"Why are you asking?","expectedAnswer":"Warum fragen Sie?"},
    {"id":5,"software":[],"promptFa":"I have a question because I want to know where it is.","expectedAnswer":"Ich habe eine Frage, weil ich wissen möchte, wo es ist."},
    {"id":6,"software":[],"promptFa":"I want to know where it is.","expectedAnswer":"Ich will wissen, wo es ist."},
    {"id":7,"software":[],"promptFa":"I would like to know where it is.","expectedAnswer":"Ich möchte wissen, wo es ist."},
    {"id":8,"software":[],"promptFa":"I want to go there.","expectedAnswer":"Ich will dorthin gehen."},
    {"id":9,"software":[],"promptFa":"I would like to go there.","expectedAnswer":"Ich möchte dorthin gehen."},
    {"id":10,"software":[],"promptFa":"It is there.","expectedAnswer":"Es ist dort."},
    {"id":11,"software":[{"german":"nichts","persian":"nothing"}],"promptFa":"I have nothing.","expectedAnswer":"Ich habe nichts."},
    {"id":12,"software":[],"promptFa":"I understand nothing.","expectedAnswer":"Ich verstehe nichts."},
    {"id":13,"software":[],"promptFa":"I see nothing.","expectedAnswer":"Ich sehe nichts."},
    {"id":14,"software":[],"promptFa":"I know nothing.","expectedAnswer":"Ich weiß nichts."},
    {"id":15,"software":[],"promptFa":"I have nothing now.","expectedAnswer":"Ich habe jetzt nichts."},
    {"id":16,"software":[],"promptFa":"I do not have it.","expectedAnswer":"Ich habe es nicht.","noteFa":"\"nicht\" negates a verb, adjective, or specific part of a sentence. \"nichts\" means \"nothing\"."},
    {"id":17,"software":[],"promptFa":"I have nothing.","expectedAnswer":"Ich habe nichts."},
    {"id":18,"software":[],"promptFa":"I do not understand it.","expectedAnswer":"Ich verstehe es nicht."},
    {"id":19,"software":[],"promptFa":"I understand nothing.","expectedAnswer":"Ich verstehe nichts."},
    {"id":20,"software":[{"german":"Wie geht es Ihnen?","persian":"How are you? (formal)"}],"promptFa":"How are you?","expectedAnswer":"Wie geht es Ihnen?"},
    {"id":21,"software":[{"german":"Wie geht es dir?","persian":"How are you? (informal)"}],"promptFa":"How are you?","expectedAnswer":"Wie geht es dir?"},
    {"id":22,"software":[{"german":"Wie geht es?","persian":"How is it going?"}],"promptFa":"How is it going?","expectedAnswer":"Wie geht es?"},
    {"id":23,"software":[],"promptFa":"I am well.","expectedAnswer":"Es geht mir gut."},
    {"id":24,"software":[],"promptFa":"I am very well.","expectedAnswer":"Es geht mir sehr gut."},
    {"id":25,"software":[],"promptFa":"Everything is going well.","expectedAnswer":"Alles geht gut."},
    {"id":26,"software":[],"promptFa":"Everything is going very well.","expectedAnswer":"Alles geht sehr gut."},
    {"id":27,"software":[{"german":"besser","persian":"better"}],"promptFa":"I am better today.","expectedAnswer":"Es geht mir heute besser."},
    {"id":28,"software":[{"german":"viel besser","persian":"much better"}],"promptFa":"I am much better today.","expectedAnswer":"Es geht mir heute viel besser."},
    {"id":29,"software":[],"promptFa":"Everything is much better today.","expectedAnswer":"Alles geht heute viel besser."},
    {"id":30,"software":[{"german":"vielen Dank","persian":"many thanks / thank you very much"}],"promptFa":"Thank you very much.","expectedAnswer":"Vielen Dank."},
    {"id":31,"software":[],"promptFa":"I am much better today, thank you very much.","expectedAnswer":"Es geht mir heute viel besser, vielen Dank."},
    {"id":32,"software":[{"german":"fühlen","persian":"to feel"}],"promptFa":"I feel it.","expectedAnswer":"Ich fühle es."},
    {"id":33,"software":[],"promptFa":"I do not feel it.","expectedAnswer":"Ich fühle es nicht."},
    {"id":34,"software":[],"promptFa":"I cannot feel it.","expectedAnswer":"Ich kann es nicht fühlen."},
    {"id":35,"software":[{"german":"sich fühlen","persian":"to feel"}],"promptFa":"I feel well.","expectedAnswer":"Ich fühle mich gut.","noteFa":"\"sich fühlen\" is reflexive. The reflexive pronoun changes with the subject: ich → mich, wir → uns, Sie → sich."},
    {"id":36,"software":[],"promptFa":"I feel very well.","expectedAnswer":"Ich fühle mich sehr gut."},
    {"id":37,"software":[],"promptFa":"I feel very well today.","expectedAnswer":"Ich fühle mich heute sehr gut."},
    {"id":38,"software":[],"promptFa":"I do not feel very well today.","expectedAnswer":"Ich fühle mich heute nicht sehr gut."},
    {"id":39,"software":[],"promptFa":"We feel well.","expectedAnswer":"Wir fühlen uns gut."},
    {"id":40,"software":[],"promptFa":"He feels well.","expectedAnswer":"Er fühlt sich gut."},
    {"id":41,"software":[],"promptFa":"She feels very well.","expectedAnswer":"Sie fühlt sich sehr gut."},
    {"id":42,"software":[],"promptFa":"How do you feel?","expectedAnswer":"Wie fühlen Sie sich?"},
    {"id":43,"software":[],"promptFa":"How do you feel today?","expectedAnswer":"Wie fühlen Sie sich heute?"},
    {"id":44,"software":[],"promptFa":"I feel much better today.","expectedAnswer":"Ich fühle mich heute viel besser."},
    {"id":45,"software":[],"promptFa":"I am much better today and I feel good.","expectedAnswer":"Es geht mir heute viel besser und ich fühle mich gut."},
    {"id":46,"software":[{"german":"waschen","persian":"to wash"}],"promptFa":"I wash it.","expectedAnswer":"Ich wasche es."},
    {"id":47,"software":[{"german":"sich waschen","persian":"to wash oneself"}],"promptFa":"I wash myself.","expectedAnswer":"Ich wasche mich."},
    {"id":48,"software":[],"promptFa":"He washes himself.","expectedAnswer":"Er wäscht sich."},
    {"id":49,"software":[],"promptFa":"We wash ourselves.","expectedAnswer":"Wir waschen uns."},
    {"id":50,"software":[],"promptFa":"You wash yourself.","expectedAnswer":"Sie waschen sich."},
    {"id":51,"software":[{"german":"sich beeilen","persian":"to hurry"}],"promptFa":"I am hurrying.","expectedAnswer":"Ich beeile mich."},
    {"id":52,"software":[],"promptFa":"We are hurrying.","expectedAnswer":"Wir beeilen uns."},
    {"id":53,"software":[],"promptFa":"He is hurrying.","expectedAnswer":"Er beeilt sich."},
    {"id":54,"software":[],"promptFa":"I have to hurry.","expectedAnswer":"Ich muss mich beeilen."},
    {"id":55,"software":[],"promptFa":"We have to hurry.","expectedAnswer":"Wir müssen uns beeilen."},
    {"id":56,"software":[],"promptFa":"He has to hurry.","expectedAnswer":"Er muss sich beeilen."},
    {"id":57,"software":[],"promptFa":"You have to hurry.","expectedAnswer":"Sie müssen sich beeilen."},
    {"id":58,"software":[{"german":"man","persian":"one / people / you in general"}],"promptFa":"One has to hurry.","expectedAnswer":"Man muss sich beeilen."},
    {"id":59,"software":[],"promptFa":"I will hurry.","expectedAnswer":"Ich werde mich beeilen."},
    {"id":60,"software":[],"promptFa":"We will hurry.","expectedAnswer":"Wir werden uns beeilen."},
    {"id":61,"software":[],"promptFa":"Can you hurry?","expectedAnswer":"Können Sie sich beeilen?"},
    {"id":62,"software":[],"promptFa":"Why are you not hurrying?","expectedAnswer":"Warum beeilen Sie sich nicht?"},
    {"id":63,"software":[],"promptFa":"Please hurry!","expectedAnswer":"Beeilen Sie sich bitte!"},
    {"id":64,"software":[{"german":"sollen","persian":"should / ought to"}],"promptFa":"You should hurry.","expectedAnswer":"Sie sollen sich beeilen.","noteFa":"\"sollen\" often expresses advice, recommendation, or what someone is supposed to do."},
    {"id":65,"software":[],"promptFa":"I should hurry.","expectedAnswer":"Ich soll mich beeilen."},
    {"id":66,"software":[],"promptFa":"We should hurry.","expectedAnswer":"Wir sollen uns beeilen."},
    {"id":67,"software":[],"promptFa":"Should I hurry?","expectedAnswer":"Soll ich mich beeilen?"},
    {"id":68,"software":[],"promptFa":"You should hurry because it is late.","expectedAnswer":"Sie sollen sich beeilen, weil es spät ist."},
    {"id":69,"software":[{"german":"sich interessieren für","persian":"to be interested in"}],"promptFa":"I am interested in the book.","expectedAnswer":"Ich interessiere mich für das Buch."},
    {"id":70,"software":[{"german":"das Buch","persian":"book"}],"promptFa":"Are you interested in the book?","expectedAnswer":"Interessieren Sie sich für das Buch?"},
    {"id":71,"software":[],"promptFa":"Are you not interested in the book?","expectedAnswer":"Interessieren Sie sich nicht für das Buch?"},
    {"id":72,"software":[],"promptFa":"Why are you not interested in the book?","expectedAnswer":"Warum interessieren Sie sich nicht für das Buch?"},
    {"id":73,"software":[],"promptFa":"He is interested in the book.","expectedAnswer":"Er interessiert sich für das Buch."},
    {"id":74,"software":[],"promptFa":"We are interested in the book.","expectedAnswer":"Wir interessieren uns für das Buch."},
    {"id":75,"software":[],"promptFa":"I am very interested in it.","expectedAnswer":"Ich interessiere mich sehr dafür."},
    {"id":76,"software":[{"german":"interessieren","persian":"to interest"}],"promptFa":"It interests me.","expectedAnswer":"Es interessiert mich."},
    {"id":77,"software":[],"promptFa":"It interests me very much.","expectedAnswer":"Es interessiert mich sehr."},
    {"id":78,"software":[],"promptFa":"That interests me.","expectedAnswer":"Das interessiert mich."},
    {"id":79,"software":[],"promptFa":"That interests me very much.","expectedAnswer":"Das interessiert mich sehr."},
    {"id":80,"software":[],"promptFa":"That does not interest me.","expectedAnswer":"Das interessiert mich nicht."},
    {"id":81,"software":[],"promptFa":"The book interests me.","expectedAnswer":"Das Buch interessiert mich.","noteFa":"Compare: \"Ich interessiere mich für das Buch\" = I am interested in the book. \"Das Buch interessiert mich\" = The book interests me."},
    {"id":82,"software":[],"promptFa":"I am interested in the book.","expectedAnswer":"Ich interessiere mich für das Buch."},
    {"id":83,"software":[{"german":"interessant","persian":"interesting"}],"promptFa":"The book is interesting.","expectedAnswer":"Das Buch ist interessant."},
    {"id":84,"software":[],"promptFa":"The book is very interesting.","expectedAnswer":"Das Buch ist sehr interessant."},
    {"id":85,"software":[],"promptFa":"I think the book is interesting.","expectedAnswer":"Ich finde das Buch interessant."},
    {"id":86,"software":[],"promptFa":"The book interests me because it is very interesting.","expectedAnswer":"Das Buch interessiert mich, weil es sehr interessant ist."},
    {"id":87,"software":[{"german":"die Freude","persian":"joy"},{"german":"sich freuen","persian":"to be happy / to be pleased"}],"promptFa":"I am happy.","expectedAnswer":"Ich freue mich."},
    {"id":88,"software":[],"promptFa":"I am very happy.","expectedAnswer":"Ich freue mich sehr."},
    {"id":89,"software":[],"promptFa":"We are happy.","expectedAnswer":"Wir freuen uns."},
    {"id":90,"software":[],"promptFa":"He is happy.","expectedAnswer":"Er freut sich."},
    {"id":91,"software":[],"promptFa":"Are you happy?","expectedAnswer":"Freuen Sie sich?"},
    {"id":92,"software":[{"german":"es freut mich","persian":"I am pleased / it makes me happy"}],"promptFa":"I am pleased.","expectedAnswer":"Es freut mich."},
    {"id":93,"software":[],"promptFa":"I am very pleased.","expectedAnswer":"Es freut mich sehr."},
    {"id":94,"software":[],"promptFa":"I am pleased that you are here.","expectedAnswer":"Es freut mich, dass Sie hier sind."},
    {"id":95,"software":[{"german":"die Zeit","persian":"time"}],"promptFa":"I have time.","expectedAnswer":"Ich habe Zeit."},
    {"id":96,"software":[{"german":"keine Zeit","persian":"no time"}],"promptFa":"I have no time.","expectedAnswer":"Ich habe keine Zeit.","noteFa":"\"kein-\" negates a noun. With \"Zeit\", use \"keine Zeit\"."},
    {"id":97,"software":[],"promptFa":"I have no time now.","expectedAnswer":"Ich habe jetzt keine Zeit."},
    {"id":98,"software":[],"promptFa":"I have no time today.","expectedAnswer":"Ich habe heute keine Zeit."},
    {"id":99,"software":[{"german":"die Zeitung","persian":"newspaper"}],"promptFa":"I have the newspaper.","expectedAnswer":"Ich habe die Zeitung."},
    {"id":100,"software":[],"promptFa":"I do not have the newspaper.","expectedAnswer":"Ich habe die Zeitung nicht."},
    {"id":101,"software":[{"german":"die Möglichkeit","persian":"possibility / opportunity"}],"promptFa":"I have the opportunity.","expectedAnswer":"Ich habe die Möglichkeit."},
    {"id":102,"software":[{"german":"keine Möglichkeit","persian":"no possibility / no opportunity"}],"promptFa":"I have no opportunity.","expectedAnswer":"Ich habe keine Möglichkeit."},
    {"id":103,"software":[],"promptFa":"I have no opportunity today.","expectedAnswer":"Ich habe heute keine Möglichkeit."},
    {"id":104,"software":[{"german":"zu + Infinitiv","persian":"to + verb"}],"promptFa":"I have time to do it.","expectedAnswer":"Ich habe Zeit, es zu tun.","noteFa":"After expressions such as \"Zeit haben\", \"Möglichkeit haben\", \"Gelegenheit haben\", \"wichtig sein\" and \"möglich sein\", German often uses \"zu + infinitive\"."},
    {"id":105,"software":[],"promptFa":"I have no time to do it.","expectedAnswer":"Ich habe keine Zeit, es zu tun."},
    {"id":106,"software":[],"promptFa":"I have time to see it.","expectedAnswer":"Ich habe Zeit, es zu sehen."},
    {"id":107,"software":[],"promptFa":"I have no time to see it.","expectedAnswer":"Ich habe keine Zeit, es zu sehen."},
    {"id":108,"software":[],"promptFa":"I have the opportunity to do it.","expectedAnswer":"Ich habe die Möglichkeit, es zu tun."},
    {"id":109,"software":[],"promptFa":"I have no opportunity to do it.","expectedAnswer":"Ich habe keine Möglichkeit, es zu tun."},
    {"id":110,"software":[{"german":"die Gelegenheit","persian":"opportunity / chance"}],"promptFa":"I have the opportunity to see it.","expectedAnswer":"Ich habe die Gelegenheit, es zu sehen."},
    {"id":111,"software":[],"promptFa":"I would like to have the opportunity to see it.","expectedAnswer":"Ich möchte die Gelegenheit haben, es zu sehen."},
    {"id":112,"software":[],"promptFa":"I would like to have the opportunity to go there.","expectedAnswer":"Ich möchte die Gelegenheit haben, dorthin zu gehen."},
    {"id":113,"software":[{"german":"immer","persian":"always"}],"promptFa":"I always have the opportunity to see it.","expectedAnswer":"Ich habe immer die Gelegenheit, es zu sehen."},
    {"id":114,"software":[],"promptFa":"I do not always have the opportunity to see it.","expectedAnswer":"Ich habe nicht immer die Gelegenheit, es zu sehen."},
    {"id":115,"software":[{"german":"oft","persian":"often"}],"promptFa":"I often have the opportunity to see it.","expectedAnswer":"Ich habe oft die Gelegenheit, es zu sehen."},
    {"id":116,"software":[],"promptFa":"I do not often have the opportunity to see it.","expectedAnswer":"Ich habe nicht oft die Gelegenheit, es zu sehen."},
    {"id":117,"software":[],"promptFa":"I do not always have time to do it.","expectedAnswer":"Ich habe nicht immer Zeit, es zu tun."},
    {"id":118,"software":[],"promptFa":"I often do not have time to do it.","expectedAnswer":"Ich habe oft keine Zeit, es zu tun."},
    {"id":119,"software":[],"promptFa":"It is possible to do it.","expectedAnswer":"Es ist möglich, es zu tun."},
    {"id":120,"software":[],"promptFa":"It is not possible to do it.","expectedAnswer":"Es ist nicht möglich, es zu tun."},
    {"id":121,"software":[],"promptFa":"It is possible to go there today.","expectedAnswer":"Es ist möglich, heute dorthin zu gehen."},
    {"id":122,"software":[],"promptFa":"It is not possible to go there today.","expectedAnswer":"Es ist nicht möglich, heute dorthin zu gehen."},
    {"id":123,"software":[{"german":"wichtig","persian":"important"}],"promptFa":"It is important.","expectedAnswer":"Es ist wichtig."},
    {"id":124,"software":[],"promptFa":"It is very important.","expectedAnswer":"Es ist sehr wichtig."},
    {"id":125,"software":[],"promptFa":"It is very important to do it.","expectedAnswer":"Es ist sehr wichtig, es zu tun."},
    {"id":126,"software":[],"promptFa":"It is important to hurry.","expectedAnswer":"Es ist wichtig, sich zu beeilen."},
    {"id":127,"software":[],"promptFa":"It is important to be here today.","expectedAnswer":"Es ist wichtig, heute hier zu sein."},
    {"id":128,"software":[],"promptFa":"It is not so important.","expectedAnswer":"Es ist nicht so wichtig."},
    {"id":129,"software":[],"promptFa":"It is not so important to do it.","expectedAnswer":"Es ist nicht so wichtig, es zu tun."},
    {"id":130,"software":[{"german":"nötig","persian":"necessary"}],"promptFa":"It is necessary.","expectedAnswer":"Es ist nötig."},
    {"id":131,"software":[],"promptFa":"It is necessary to do it.","expectedAnswer":"Es ist nötig, es zu tun."},
    {"id":132,"software":[],"promptFa":"It is not necessary.","expectedAnswer":"Es ist nicht nötig."},
    {"id":133,"software":[],"promptFa":"It is not necessary to do it now.","expectedAnswer":"Es ist nicht nötig, es jetzt zu tun."},
    {"id":134,"software":[],"promptFa":"It is not necessary to go there today.","expectedAnswer":"Es ist nicht nötig, heute dorthin zu gehen."},
    {"id":135,"software":[],"promptFa":"It is necessary to hurry.","expectedAnswer":"Es ist nötig, sich zu beeilen."},
    {"id":136,"software":[{"german":"spät","persian":"late"}],"promptFa":"It is late.","expectedAnswer":"Es ist spät."},
    {"id":137,"software":[],"promptFa":"It is very late.","expectedAnswer":"Es ist sehr spät."},
    {"id":138,"software":[],"promptFa":"We have to hurry because it is late.","expectedAnswer":"Wir müssen uns beeilen, weil es spät ist."},
    {"id":139,"software":[],"promptFa":"You should hurry because it is very late.","expectedAnswer":"Sie sollen sich beeilen, weil es sehr spät ist."},
    {"id":140,"software":[],"promptFa":"I have no time because I have to go now.","expectedAnswer":"Ich habe keine Zeit, weil ich jetzt gehen muss."},
    {"id":141,"software":[],"promptFa":"I have no time to do it now.","expectedAnswer":"Ich habe keine Zeit, es jetzt zu tun."},
    {"id":142,"software":[],"promptFa":"I would like to do it, but I have no time.","expectedAnswer":"Ich möchte es tun, aber ich habe keine Zeit."},
    {"id":143,"software":[],"promptFa":"I would like to go there, but I have no opportunity today.","expectedAnswer":"Ich möchte dorthin gehen, aber ich habe heute keine Möglichkeit."},
    {"id":144,"software":[],"promptFa":"I am interested in it, but I have no time to see it.","expectedAnswer":"Ich interessiere mich dafür, aber ich habe keine Zeit, es zu sehen."},
    {"id":145,"software":[],"promptFa":"The book interests me very much.","expectedAnswer":"Das Buch interessiert mich sehr."},
    {"id":146,"software":[],"promptFa":"I would like to have the opportunity to read it.","expectedAnswer":"Ich möchte die Gelegenheit haben, es zu lesen."},
    {"id":147,"software":[{"german":"lesen","persian":"to read"}],"promptFa":"I like reading the book.","expectedAnswer":"Ich lese das Buch gern."},
    {"id":148,"software":[],"promptFa":"I am interested in the book and I would like to read it.","expectedAnswer":"Ich interessiere mich für das Buch und ich möchte es lesen."},
    {"id":149,"software":[],"promptFa":"I do not have time to read it today.","expectedAnswer":"Ich habe heute keine Zeit, es zu lesen."},
    {"id":150,"software":[],"promptFa":"It is important to read it.","expectedAnswer":"Es ist wichtig, es zu lesen."},
    {"id":151,"software":[],"promptFa":"It is not necessary to read it today.","expectedAnswer":"Es ist nicht nötig, es heute zu lesen."},
    {"id":152,"software":[],"promptFa":"How are you today?","expectedAnswer":"Wie geht es Ihnen heute?"},
    {"id":153,"software":[],"promptFa":"I am much better today.","expectedAnswer":"Es geht mir heute viel besser."},
    {"id":154,"software":[],"promptFa":"How do you feel today?","expectedAnswer":"Wie fühlen Sie sich heute?"},
    {"id":155,"software":[],"promptFa":"I feel much better today.","expectedAnswer":"Ich fühle mich heute viel besser."},
    {"id":156,"software":[],"promptFa":"I am happy that you feel better.","expectedAnswer":"Ich freue mich, dass Sie sich besser fühlen."},
    {"id":157,"software":[],"promptFa":"We have to hurry.","expectedAnswer":"Wir müssen uns beeilen."},
    {"id":158,"software":[],"promptFa":"Why do we have to hurry?","expectedAnswer":"Warum müssen wir uns beeilen?"},
    {"id":159,"software":[],"promptFa":"We have to hurry because it is very late.","expectedAnswer":"Wir müssen uns beeilen, weil es sehr spät ist."},
    {"id":160,"software":[],"promptFa":"Are you interested in this?","expectedAnswer":"Interessieren Sie sich dafür?"},
    {"id":161,"software":[],"promptFa":"Yes, I am very interested in it.","expectedAnswer":"Ja, ich interessiere mich sehr dafür."},
    {"id":162,"software":[],"promptFa":"Why are you interested in it?","expectedAnswer":"Warum interessieren Sie sich dafür?"},
    {"id":163,"software":[],"promptFa":"I am interested in it because it is very interesting.","expectedAnswer":"Ich interessiere mich dafür, weil es sehr interessant ist."},
    {"id":164,"software":[],"promptFa":"Do you have time to see it today?","expectedAnswer":"Haben Sie heute Zeit, es zu sehen?"},
    {"id":165,"software":[],"promptFa":"No, I do not have time to see it today.","expectedAnswer":"Nein, ich habe heute keine Zeit, es zu sehen."},
    {"id":166,"software":[],"promptFa":"Do you have the opportunity to see it tomorrow?","expectedAnswer":"Haben Sie morgen die Gelegenheit, es zu sehen?"},
    {"id":167,"software":[],"promptFa":"Yes, I will have the opportunity to see it tomorrow.","expectedAnswer":"Ja, ich werde morgen die Gelegenheit haben, es zu sehen."},
    {"id":168,"software":[],"promptFa":"Is it possible to do it today?","expectedAnswer":"Ist es möglich, es heute zu tun?"},
    {"id":169,"software":[],"promptFa":"No, it is not possible to do it today.","expectedAnswer":"Nein, es ist nicht möglich, es heute zu tun."},
    {"id":170,"software":[],"promptFa":"Is it necessary to do it now?","expectedAnswer":"Ist es nötig, es jetzt zu tun?"},
    {"id":171,"software":[],"promptFa":"No, it is not necessary to do it now.","expectedAnswer":"Nein, es ist nicht nötig, es jetzt zu tun."},
    {"id":172,"software":[],"promptFa":"Is it important to do it today?","expectedAnswer":"Ist es wichtig, es heute zu tun?"},
    {"id":173,"software":[],"promptFa":"Yes, it is very important to do it today.","expectedAnswer":"Ja, es ist sehr wichtig, es heute zu tun."},
    {"id":174,"software":[],"promptFa":"I have a question.","expectedAnswer":"Ich habe eine Frage."},
    {"id":175,"software":[],"promptFa":"I would like to know if it is possible to do it today.","expectedAnswer":"Ich möchte wissen, ob es möglich ist, es heute zu tun."},
    {"id":176,"software":[{"german":"ob","persian":"whether / if"}],"promptFa":"I do not know whether it is possible.","expectedAnswer":"Ich weiß nicht, ob es möglich ist.","noteFa":"\"ob\" introduces an indirect yes/no question."},
    {"id":177,"software":[],"promptFa":"Can you tell me whether it is possible?","expectedAnswer":"Können Sie mir sagen, ob es möglich ist?"},
    {"id":178,"software":[],"promptFa":"I would like to know whether you have time today.","expectedAnswer":"Ich möchte wissen, ob Sie heute Zeit haben."},
    {"id":179,"software":[],"promptFa":"I would like to know whether you are interested in it.","expectedAnswer":"Ich möchte wissen, ob Sie sich dafür interessieren."},
    {"id":180,"software":[],"promptFa":"I do not know whether I will have time tomorrow.","expectedAnswer":"Ich weiß nicht, ob ich morgen Zeit haben werde."},
    {"id":181,"software":[],"promptFa":"I feel much better today, but I still have no time.","expectedAnswer":"Ich fühle mich heute viel besser, aber ich habe trotzdem keine Zeit."},
    {"id":182,"software":[],"promptFa":"I am interested in it and I would like to have the opportunity to see it.","expectedAnswer":"Ich interessiere mich dafür und ich möchte die Gelegenheit haben, es zu sehen."},
    {"id":183,"software":[],"promptFa":"I do not always have the opportunity to see it.","expectedAnswer":"Ich habe nicht immer die Gelegenheit, es zu sehen."},
    {"id":184,"software":[],"promptFa":"It is not possible to go there today because I have no time.","expectedAnswer":"Es ist nicht möglich, heute dorthin zu gehen, weil ich keine Zeit habe."},
    {"id":185,"software":[],"promptFa":"It is very important to hurry because it is already late.","expectedAnswer":"Es ist sehr wichtig, sich zu beeilen, weil es schon spät ist."},
    {"id":186,"software":[],"promptFa":"I would like to go there, but it is not necessary to go there today.","expectedAnswer":"Ich möchte dorthin gehen, aber es ist nicht nötig, heute dorthin zu gehen."},
  ],
};
