// Lesson 2 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Replaces the old plain-reading "Lektion 2" course content (server/content/
// deutsch-almani-lektionen/lektion-2.txt) with an interactive version, same
// pattern as lesson1.js - see main.js's INTERACTIVE_LESSONS map, which
// intercepts the "deutsch-almani-lektion-2" course card (still a plain
// courses-table row, just for the level/title/grid-card metadata) and
// renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.

export const lektion2 = {
  id: 'lektion2',
  courseId: 'deutsch-almani-lektion-2',
  title: "Lektion 2 – Haben, Bringen, Brauchen und Zukunft",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-2-v1',
  promptLang: 'en',
  // This lesson stays in the formal register throughout (Sie/Ihnen) - the
  // one "sie" occurrence (step 44, "Brauchen sie es?") is the unrelated
  // 3rd-person-plural "they", not the formal address form.
  registerHotwords: ['Sie'],
  steps: [
    {"id":1,"software":[{"german":"verstehen","persian":"to understand"},{"german":"Sie","persian":"you, formal"}],"promptFa":"I understand you.","expectedAnswer":"Ich verstehe Sie."},
    {"id":2,"software":[{"german":"sehr gut","persian":"very well"}],"promptFa":"I understand you very well.","expectedAnswer":"Ich verstehe Sie sehr gut."},
    {"id":3,"software":[{"german":"nicht","persian":"not"}],"promptFa":"I do not understand you very well.","expectedAnswer":"Ich verstehe Sie nicht sehr gut."},
    {"id":4,"software":[{"german":"können","persian":"can / to be able to"}],"promptFa":"I cannot understand you very well.","expectedAnswer":"Ich kann Sie nicht sehr gut verstehen.","noteFa":"With a modal verb such as \"können\", the second verb goes to the end in the infinitive."},
    {"id":5,"software":[{"german":"mich","persian":"me"}],"promptFa":"Do you understand me?","expectedAnswer":"Verstehen Sie mich?","noteFa":"In a yes/no question, the conjugated verb comes before the subject."},
    {"id":6,"software":[{"german":"bringen","persian":"to bring"},{"german":"mir","persian":"to me"}],"promptFa":"Do you want to bring it to me?","expectedAnswer":"Wollen Sie es mir bringen?"},
    {"id":7,"software":[{"german":"heute","persian":"today"}],"promptFa":"Can you bring it to me today?","expectedAnswer":"Können Sie es mir heute bringen?"},
    {"id":8,"software":[{"german":"haben","persian":"to have"}],"promptFa":"We have it.","expectedAnswer":"Wir haben es."},
    {"id":9,"software":[],"promptFa":"We do not have it.","expectedAnswer":"Wir haben es nicht."},
    {"id":10,"software":[],"promptFa":"Do you have it?","expectedAnswer":"Haben Sie es?","noteFa":"In a yes/no question, \"haben\" comes before \"Sie\"."},
    {"id":11,"software":[{"german":"warum","persian":"why"}],"promptFa":"Why don't you have it?","expectedAnswer":"Warum haben Sie es nicht?"},
    {"id":12,"software":[{"german":"mit mir","persian":"with me"}],"promptFa":"Can you come with me?","expectedAnswer":"Können Sie mit mir kommen?"},
    {"id":13,"software":[{"german":"für mich","persian":"for me"}],"promptFa":"Do you have it for me?","expectedAnswer":"Haben Sie es für mich?"},
    {"id":14,"software":[{"german":"was","persian":"what"}],"promptFa":"What do you have for me?","expectedAnswer":"Was haben Sie für mich?"},
    {"id":15,"software":[],"promptFa":"It is for me.","expectedAnswer":"Es ist für mich."},
    {"id":16,"software":[],"promptFa":"Can you understand me?","expectedAnswer":"Können Sie mich verstehen?"},
    {"id":17,"software":[],"promptFa":"Why can't you understand me?","expectedAnswer":"Warum können Sie mich nicht verstehen?","noteFa":"With \"warum\", the question word comes first, followed by the conjugated verb."},
    {"id":18,"software":[{"german":"etwas","persian":"something"}],"promptFa":"Can you bring me something?","expectedAnswer":"Können Sie mir etwas bringen?"},
    {"id":19,"software":[{"german":"jetzt","persian":"now"}],"promptFa":"Can you bring me something now?","expectedAnswer":"Können Sie mir jetzt etwas bringen?"},
    {"id":20,"software":[],"promptFa":"What can you bring me?","expectedAnswer":"Was können Sie mir bringen?"},
    {"id":21,"software":[],"promptFa":"Why can't you bring it to me now?","expectedAnswer":"Warum können Sie es mir jetzt nicht bringen?"},
    {"id":22,"software":[{"german":"müssen","persian":"must / to have to"}],"promptFa":"I must have it.","expectedAnswer":"Ich muss es haben."},
    {"id":23,"software":[{"german":"leider","persian":"unfortunately"},{"german":"tun","persian":"to do"}],"promptFa":"Unfortunately, I cannot do it now.","expectedAnswer":"Ich kann es leider jetzt nicht tun."},
    {"id":24,"software":[{"german":"es tut mir leid","persian":"I am sorry"}],"promptFa":"I am sorry, but I do not have it for you now.","expectedAnswer":"Es tut mir leid, aber ich habe es jetzt nicht für Sie."},
    {"id":25,"software":[{"german":"Ihnen","persian":"to you, formal"}],"promptFa":"I cannot bring it to you now.","expectedAnswer":"Ich kann es Ihnen jetzt nicht bringen.","noteFa":"\"Sie\" means formal \"you\", while \"Ihnen\" means \"to you\" in the dative."},
    {"id":26,"software":[{"german":"denn","persian":"because"}],"promptFa":"because I do not have it now","expectedAnswer":"denn ich habe es jetzt nicht","noteFa":"Unlike \"weil\", \"denn\" does not send the conjugated verb to the end. Normal main-clause word order stays."},
    {"id":27,"software":[],"promptFa":"I cannot bring it to you today because I do not have it.","expectedAnswer":"Ich kann es Ihnen heute nicht bringen, denn ich habe es nicht."},
    {"id":28,"software":[],"promptFa":"We must.","expectedAnswer":"Wir müssen."},
    {"id":29,"software":[],"promptFa":"You must.","expectedAnswer":"Sie müssen."},
    {"id":30,"software":[],"promptFa":"You must come with me.","expectedAnswer":"Sie müssen mit mir kommen."},
    {"id":31,"software":[{"german":"geben","persian":"to give"}],"promptFa":"I give.","expectedAnswer":"Ich gebe."},
    {"id":32,"software":[],"promptFa":"I give it to you.","expectedAnswer":"Ich gebe es Ihnen."},
    {"id":33,"software":[],"promptFa":"But I cannot give it to you today because I do not have it.","expectedAnswer":"Aber ich kann es Ihnen heute nicht geben, denn ich habe es nicht."},
    {"id":34,"software":[{"german":"wann","persian":"when"}],"promptFa":"When do you want to have it?","expectedAnswer":"Wann wollen Sie es haben?"},
    {"id":35,"software":[],"promptFa":"When do you want to have it for me?","expectedAnswer":"Wann wollen Sie es für mich haben?"},
    {"id":36,"software":[],"promptFa":"When can you have it for me?","expectedAnswer":"Wann können Sie es für mich haben?"},
    {"id":37,"software":[{"german":"rauchen","persian":"to smoke"}],"promptFa":"I do not smoke.","expectedAnswer":"Ich rauche nicht."},
    {"id":38,"software":[{"german":"verboten","persian":"forbidden"}],"promptFa":"Smoking is forbidden.","expectedAnswer":"Rauchen ist verboten."},
    {"id":39,"software":[{"german":"auch","persian":"also"}],"promptFa":"Me too.","expectedAnswer":"Ich auch."},
    {"id":40,"software":[{"german":"brauchen","persian":"to need"}],"promptFa":"I need it.","expectedAnswer":"Ich brauche es."},
    {"id":41,"software":[],"promptFa":"I do not need it.","expectedAnswer":"Ich brauche es nicht."},
    {"id":42,"software":[],"promptFa":"I do not need it now.","expectedAnswer":"Ich brauche es jetzt nicht."},
    {"id":43,"software":[{"german":"sie","persian":"they"}],"promptFa":"Do they need it?","expectedAnswer":"Brauchen sie es?"},
    {"id":44,"software":[],"promptFa":"When do you need it?","expectedAnswer":"Wann brauchen Sie es?"},
    {"id":45,"software":[],"promptFa":"I can bring it to you today.","expectedAnswer":"Ich kann es Ihnen heute bringen."},
    {"id":46,"software":[],"promptFa":"I want to have it.","expectedAnswer":"Ich will es haben."},
    {"id":47,"software":[{"german":"werden","persian":"will / to become"}],"promptFa":"We will have it.","expectedAnswer":"Wir werden es haben.","noteFa":"German can form the future with \"werden + infinitive\". The infinitive goes to the end."},
    {"id":48,"software":[],"promptFa":"They will have it.","expectedAnswer":"Sie werden es haben."},
    {"id":49,"software":[],"promptFa":"When will they have it for me?","expectedAnswer":"Wann werden sie es für mich haben?"},
    {"id":50,"software":[],"promptFa":"I will have it for you today.","expectedAnswer":"Ich werde es heute für Sie haben."},
    {"id":51,"software":[],"promptFa":"I will have it today.","expectedAnswer":"Ich werde es heute haben."},
    {"id":52,"software":[{"german":"heute Abend","persian":"this evening"},{"german":"sehen","persian":"to see"}],"promptFa":"I will see it this evening.","expectedAnswer":"Ich werde es heute Abend sehen."},
    {"id":53,"software":[],"promptFa":"I will bring it to you.","expectedAnswer":"Ich werde es Ihnen bringen."},
    {"id":54,"software":[],"promptFa":"When can you bring it to me?","expectedAnswer":"Wann können Sie es mir bringen?"},
    {"id":55,"software":[],"promptFa":"When do you want to bring it to me?","expectedAnswer":"Wann wollen Sie es mir bringen?"},
    {"id":56,"software":[],"promptFa":"When will you bring it to me?","expectedAnswer":"Wann werden Sie es mir bringen?"},
    {"id":57,"software":[],"promptFa":"When can you bring it to me, because I need it today?","expectedAnswer":"Wann können Sie es mir bringen, denn ich brauche es heute?"},
    {"id":58,"software":[],"promptFa":"I want to have it today because I need it today.","expectedAnswer":"Ich will es heute haben, denn ich brauche es heute."},
    {"id":59,"software":[{"german":"um wie viel Uhr","persian":"at what time"}],"promptFa":"At what time do you want to have it?","expectedAnswer":"Um wie viel Uhr wollen Sie es haben?"},
    {"id":60,"software":[{"german":"sein","persian":"to be"},{"german":"hier","persian":"here"}],"promptFa":"At what time can you be here this evening?","expectedAnswer":"Um wie viel Uhr können Sie heute Abend hier sein?"},
    {"id":61,"software":[],"promptFa":"At what time do you want to be here?","expectedAnswer":"Um wie viel Uhr wollen Sie hier sein?"},
    {"id":62,"software":[],"promptFa":"At what time will you be here?","expectedAnswer":"Um wie viel Uhr werden Sie hier sein?"},
    {"id":63,"software":[{"german":"ankommen","persian":"to arrive"},{"german":"morgen","persian":"tomorrow"}],"promptFa":"At what time will you arrive tomorrow?","expectedAnswer":"Um wie viel Uhr werden Sie morgen ankommen?"},
    {"id":64,"software":[],"promptFa":"At what time can you be here tomorrow?","expectedAnswer":"Um wie viel Uhr können Sie morgen hier sein?"},
    {"id":65,"software":[{"german":"wie lange","persian":"how long"},{"german":"bleiben","persian":"to stay"}],"promptFa":"How long can you stay here today?","expectedAnswer":"Wie lange können Sie heute hier bleiben?"},
    {"id":66,"software":[],"promptFa":"How long will you stay here?","expectedAnswer":"Wie lange werden Sie hier bleiben?"},
    {"id":67,"software":[{"german":"warten","persian":"to wait"}],"promptFa":"I wait.","expectedAnswer":"Ich warte."},
    {"id":68,"software":[{"german":"bitte","persian":"please"}],"promptFa":"Will you please do it for me?","expectedAnswer":"Wollen Sie es bitte für mich tun?"},
    {"id":69,"software":[],"promptFa":"When will you do it for me?","expectedAnswer":"Wann werden Sie es für mich tun?"},
    {"id":70,"software":[],"promptFa":"Will you please stay here with me?","expectedAnswer":"Wollen Sie bitte mit mir hier bleiben?"},
    {"id":71,"software":[],"promptFa":"How long will you stay?","expectedAnswer":"Wie lange werden Sie bleiben?"},
    {"id":72,"software":[{"german":"sagen","persian":"to say / to tell"}],"promptFa":"Do you want to tell me?","expectedAnswer":"Wollen Sie mir sagen?"},
    {"id":73,"software":[],"promptFa":"When will you tell me?","expectedAnswer":"Wann werden Sie mir sagen?"},
    {"id":74,"software":[{"german":"wo","persian":"where"}],"promptFa":"Do you want to tell me where it is?","expectedAnswer":"Wollen Sie mir sagen, wo es ist?"},
    {"id":75,"software":[{"german":"finden","persian":"to find"}],"promptFa":"I cannot find it.","expectedAnswer":"Ich kann es nicht finden."},
    {"id":76,"software":[],"promptFa":"Do you want to tell me where it is, because I cannot find it?","expectedAnswer":"Wollen Sie mir sagen, wo es ist, denn ich kann es nicht finden?"},
    {"id":77,"software":[{"german":"wissen","persian":"to know"}],"promptFa":"I do not know.","expectedAnswer":"Ich weiß nicht."},
    {"id":78,"software":[],"promptFa":"I do not know where it is.","expectedAnswer":"Ich weiß nicht, wo es ist.","noteFa":"\"wo es ist\" is an embedded question. The verb goes to the end of this clause."},
    {"id":79,"software":[],"promptFa":"I am sorry, but I do not know where it is. I cannot find it.","expectedAnswer":"Es tut mir leid, aber ich weiß nicht, wo es ist. Ich kann es nicht finden."},
  ],
};
