// Lesson 9 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/.../lektion8.js - see main.js's
// INTERACTIVE_LESSONS map, which intercepts the "deutsch-almani-lektion-9"
// course card (a plain courses-table row, just for the level/title/grid-
// card metadata) and renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.
//
// Unlike earlier Lektionen, this one introduces the informal "du" register
// alongside "Sie" (du bist/bleibst/wirst/willst/kannst/möchtest/weißt/
// könntest/hast/hattest/warst forms), so registerHotwords stays empty -
// there is no single consistent register to highlight.

export const lektion9 = {
  id: 'lektion9',
  courseId: 'deutsch-almani-lektion-9',
  title: "Lektion 9 – Du-Form, Perfekt, Noch und Vergangenheit",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-9-v1',
  promptLang: 'en',
  steps: [
    {"id":1,"software":[{"german":"du","persian":"you, informal singular"}],"promptFa":"You are here.","expectedAnswer":"Du bist hier."},
    {"id":2,"software":[{"german":"bleibst","persian":"stay, for \"du\""}],"promptFa":"You stay here.","expectedAnswer":"Du bleibst hier."},
    {"id":3,"software":[],"promptFa":"How long are you staying here?","expectedAnswer":"Wie lange bleibst du hier?"},
    {"id":4,"software":[],"promptFa":"How long are you staying?","expectedAnswer":"Wie lange bleibst du?"},
    {"id":5,"software":[{"german":"wirst","persian":"will, for \"du\""}],"promptFa":"You will stay here.","expectedAnswer":"Du wirst hier bleiben."},
    {"id":6,"software":[],"promptFa":"How long will you stay here?","expectedAnswer":"Wie lange wirst du hier bleiben?"},
    {"id":7,"software":[],"promptFa":"I do not know how long you will stay here.","expectedAnswer":"Ich weiß nicht, wie lange du hier bleiben wirst."},
    {"id":8,"software":[],"promptFa":"I do not know how long he will stay here.","expectedAnswer":"Ich weiß nicht, wie lange er hier bleiben wird."},
    {"id":9,"software":[{"german":"willst","persian":"want, for \"du\""}],"promptFa":"You want to stay here.","expectedAnswer":"Du willst hier bleiben."},
    {"id":10,"software":[],"promptFa":"Where do you want to wait for me?","expectedAnswer":"Wo willst du auf mich warten?"},
    {"id":11,"software":[],"promptFa":"Why do you not want to do it?","expectedAnswer":"Warum willst du es nicht tun?"},
    {"id":12,"software":[{"german":"kannst","persian":"can, for \"du\""}],"promptFa":"You can come with me.","expectedAnswer":"Du kannst mit mir kommen."},
    {"id":13,"software":[],"promptFa":"Can you do it?","expectedAnswer":"Kannst du es tun?"},
    {"id":14,"software":[],"promptFa":"Can you find it?","expectedAnswer":"Kannst du es finden?"},
    {"id":15,"software":[{"german":"möchtest","persian":"would like, for \"du\""}],"promptFa":"You would like to come with me.","expectedAnswer":"Du möchtest mit mir kommen."},
    {"id":16,"software":[],"promptFa":"Would you like to stay here?","expectedAnswer":"Möchtest du hier bleiben?"},
    {"id":17,"software":[{"german":"weißt","persian":"know, for \"du\""}],"promptFa":"You know it.","expectedAnswer":"Du weißt es."},
    {"id":18,"software":[],"promptFa":"Do you know where it is?","expectedAnswer":"Weißt du, wo es ist?"},
    {"id":19,"software":[],"promptFa":"I know it, he knows it, and you know it.","expectedAnswer":"Ich weiß es, er weiß es und du weißt es."},
    {"id":20,"software":[{"german":"lesen","persian":"to read"}],"promptFa":"I will read the newspaper.","expectedAnswer":"Ich werde die Zeitung lesen."},
    {"id":21,"software":[],"promptFa":"Do you want to read the newspaper?","expectedAnswer":"Willst du die Zeitung lesen?"},
    {"id":22,"software":[],"promptFa":"I would like to read the newspaper.","expectedAnswer":"Ich möchte die Zeitung lesen."},
    {"id":23,"software":[{"german":"könntest","persian":"could, informal \"du\""}],"promptFa":"Could you come with me?","expectedAnswer":"Könntest du mit mir kommen?"},
    {"id":24,"software":[],"promptFa":"Could you tell me where it is?","expectedAnswer":"Könntest du mir sagen, wo es ist?"},
    {"id":25,"software":[],"promptFa":"Could you wait for me here?","expectedAnswer":"Könntest du hier auf mich warten?"},
    {"id":26,"software":[{"german":"hat","persian":"has, for \"er/sie/es\""}],"promptFa":"He has it.","expectedAnswer":"Er hat es."},
    {"id":27,"software":[],"promptFa":"He has no time.","expectedAnswer":"Er hat keine Zeit."},
    {"id":28,"software":[{"german":"hast","persian":"have, for \"du\""}],"promptFa":"You have it.","expectedAnswer":"Du hast es."},
    {"id":29,"software":[],"promptFa":"Do you have time?","expectedAnswer":"Hast du Zeit?"},
    {"id":30,"software":[{"german":"Recht","persian":"right / to be right"}],"promptFa":"You are right.","expectedAnswer":"Du hast Recht."},
    {"id":31,"software":[],"promptFa":"You are right.","expectedAnswer":"Sie haben Recht."},
    {"id":32,"software":[{"german":"rechts","persian":"on the right / right-hand side"}],"promptFa":"It is on the right.","expectedAnswer":"Es ist rechts."},
    {"id":33,"software":[],"promptFa":"The door is on the right.","expectedAnswer":"Die Tür ist rechts."},
    {"id":34,"software":[{"german":"gekauft","persian":"bought"}],"promptFa":"I bought it.","expectedAnswer":"Ich habe es gekauft.","noteFa":"The Perfekt is commonly formed with \"haben + Partizip II\". \"kaufen\" becomes \"gekauft\"."},
    {"id":35,"software":[],"promptFa":"I did not buy it.","expectedAnswer":"Ich habe es nicht gekauft."},
    {"id":36,"software":[],"promptFa":"Did you buy it?","expectedAnswer":"Haben Sie es gekauft?"},
    {"id":37,"software":[],"promptFa":"Did you buy it?","expectedAnswer":"Hast du es gekauft?"},
    {"id":38,"software":[{"german":"noch","persian":"still / yet / more"}],"promptFa":"I want some more.","expectedAnswer":"Ich will noch etwas."},
    {"id":39,"software":[],"promptFa":"I want to eat some more.","expectedAnswer":"Ich will noch etwas essen."},
    {"id":40,"software":[{"german":"wenig","persian":"little"}],"promptFa":"I want a little more.","expectedAnswer":"Ich will noch ein wenig."},
    {"id":41,"software":[{"german":"bisschen","persian":"little / a bit"}],"promptFa":"I want a little more.","expectedAnswer":"Ich will noch ein bisschen."},
    {"id":42,"software":[],"promptFa":"He has not bought it yet.","expectedAnswer":"Er hat es noch nicht gekauft.","noteFa":"\"noch nicht\" means \"not yet\"."},
    {"id":43,"software":[],"promptFa":"Why have you not bought it yet?","expectedAnswer":"Warum haben Sie es noch nicht gekauft?"},
    {"id":44,"software":[],"promptFa":"Why have you not bought it yet?","expectedAnswer":"Warum hast du es noch nicht gekauft?"},
    {"id":45,"software":[],"promptFa":"I have not done it yet.","expectedAnswer":"Ich habe es noch nicht getan."},
    {"id":46,"software":[{"german":"gemacht","persian":"done / made"}],"promptFa":"He did it.","expectedAnswer":"Er hat es gemacht."},
    {"id":47,"software":[],"promptFa":"Have you done it?","expectedAnswer":"Hast du es gemacht?"},
    {"id":48,"software":[],"promptFa":"He has not done it yet.","expectedAnswer":"Er hat es noch nicht gemacht."},
    {"id":49,"software":[{"german":"lachen","persian":"to laugh"}],"promptFa":"He laughs.","expectedAnswer":"Er lacht."},
    {"id":50,"software":[{"german":"gelacht","persian":"laughed"}],"promptFa":"He laughed.","expectedAnswer":"Er hat gelacht."},
    {"id":51,"software":[],"promptFa":"We laughed.","expectedAnswer":"Wir haben gelacht."},
    {"id":52,"software":[{"german":"verkaufen","persian":"to sell"}],"promptFa":"I want to sell it.","expectedAnswer":"Ich will es verkaufen."},
    {"id":53,"software":[],"promptFa":"Will you sell it?","expectedAnswer":"Werden Sie es verkaufen?"},
    {"id":54,"software":[{"german":"zurückkommen","persian":"to come back / return"}],"promptFa":"He will come back soon.","expectedAnswer":"Er wird bald zurückkommen."},
    {"id":55,"software":[],"promptFa":"When will you come back?","expectedAnswer":"Wann werden Sie zurückkommen?"},
    {"id":56,"software":[{"german":"Rücken","persian":"back, body part"}],"promptFa":"My back.","expectedAnswer":"Mein Rücken."},
    {"id":57,"software":[{"german":"zurück","persian":"back"}],"promptFa":"He is coming back soon.","expectedAnswer":"Er kommt bald zurück."},
    {"id":58,"software":[],"promptFa":"I will come back tomorrow.","expectedAnswer":"Ich werde morgen zurückkommen."},
    {"id":59,"software":[{"german":"verkaufe","persian":"I sell"}],"promptFa":"I sell it.","expectedAnswer":"Ich verkaufe es."},
    {"id":60,"software":[{"german":"verkauft","persian":"sold"}],"promptFa":"I sold it.","expectedAnswer":"Ich habe es verkauft."},
    {"id":61,"software":[],"promptFa":"He sold it.","expectedAnswer":"Er hat es verkauft."},
    {"id":62,"software":[],"promptFa":"We sold it.","expectedAnswer":"Wir haben es verkauft."},
    {"id":63,"software":[],"promptFa":"You sold it.","expectedAnswer":"Sie haben es verkauft."},
    {"id":64,"software":[],"promptFa":"You sold it.","expectedAnswer":"Du hast es verkauft."},
    {"id":65,"software":[],"promptFa":"Why did you sell it?","expectedAnswer":"Warum hast du es verkauft?"},
    {"id":66,"software":[],"promptFa":"Why did you not sell it?","expectedAnswer":"Warum haben Sie es nicht verkauft?"},
    {"id":67,"software":[],"promptFa":"He has not sold it yet.","expectedAnswer":"Er hat es noch nicht verkauft."},
    {"id":68,"software":[],"promptFa":"Why have you not sold it yet?","expectedAnswer":"Warum haben Sie es noch nicht verkauft?"},
    {"id":69,"software":[],"promptFa":"Why have you not sold it yet?","expectedAnswer":"Warum hast du es noch nicht verkauft?"},
    {"id":70,"software":[{"german":"einkaufen","persian":"to shop / go shopping"}],"promptFa":"I am going shopping.","expectedAnswer":"Ich kaufe ein."},
    {"id":71,"software":[{"german":"eingekauft","persian":"shopped"}],"promptFa":"I went shopping.","expectedAnswer":"Ich habe eingekauft."},
    {"id":72,"software":[],"promptFa":"We went shopping.","expectedAnswer":"Wir haben eingekauft."},
    {"id":73,"software":[{"german":"gesagt","persian":"said / told"}],"promptFa":"He told me.","expectedAnswer":"Er hat mir gesagt."},
    {"id":74,"software":[],"promptFa":"We told you.","expectedAnswer":"Wir haben es Ihnen gesagt."},
    {"id":75,"software":[],"promptFa":"We told you.","expectedAnswer":"Wir haben es dir gesagt."},
    {"id":76,"software":[],"promptFa":"Why did you not tell me?","expectedAnswer":"Warum haben Sie mir nicht gesagt?"},
    {"id":77,"software":[],"promptFa":"He told me that he would not do it.","expectedAnswer":"Er hat mir gesagt, dass er es nicht tun würde."},
    {"id":78,"software":[],"promptFa":"He did not tell me that he would do it.","expectedAnswer":"Er hat mir nicht gesagt, dass er es tun wird."},
    {"id":79,"software":[{"german":"repariere","persian":"I repair"}],"promptFa":"I repair it.","expectedAnswer":"Ich repariere es."},
    {"id":80,"software":[{"german":"repariert","persian":"repairs / repaired"}],"promptFa":"He repairs it.","expectedAnswer":"Er repariert es."},
    {"id":81,"software":[],"promptFa":"I repaired it.","expectedAnswer":"Ich habe es repariert.","noteFa":"Verbs ending in \"-ieren\" form the Partizip II without \"ge-\": reparieren → repariert."},
    {"id":82,"software":[],"promptFa":"He repaired it.","expectedAnswer":"Er hat es repariert."},
    {"id":83,"software":[{"german":"organisieren","persian":"to organize"}],"promptFa":"I organize it.","expectedAnswer":"Ich organisiere es."},
    {"id":84,"software":[{"german":"organisiert","persian":"organized"}],"promptFa":"He organized it.","expectedAnswer":"Er hat es organisiert."},
    {"id":85,"software":[],"promptFa":"It is very well organized.","expectedAnswer":"Es ist sehr gut organisiert."},
    {"id":86,"software":[],"promptFa":"Everything is very well organized.","expectedAnswer":"Alles ist sehr gut organisiert."},
    {"id":87,"software":[{"german":"spezialisieren","persian":"to specialize"}],"promptFa":"I want to specialize.","expectedAnswer":"Ich möchte mich spezialisieren."},
    {"id":88,"software":[],"promptFa":"He wants to specialize.","expectedAnswer":"Er möchte sich spezialisieren."},
    {"id":89,"software":[{"german":"kontrollieren","persian":"to check / control"}],"promptFa":"I check it.","expectedAnswer":"Ich kontrolliere es."},
    {"id":90,"software":[{"german":"kontrolliert","persian":"checked / controlled"}],"promptFa":"He checked it.","expectedAnswer":"Er hat es kontrolliert."},
    {"id":91,"software":[],"promptFa":"Have you checked it?","expectedAnswer":"Haben Sie es kontrolliert?"},
    {"id":92,"software":[],"promptFa":"I have already checked it.","expectedAnswer":"Ich habe es schon kontrolliert."},
    {"id":93,"software":[{"german":"hattest","persian":"had, for \"du\""}],"promptFa":"You had it.","expectedAnswer":"Du hattest es."},
    {"id":94,"software":[],"promptFa":"Did you have time?","expectedAnswer":"Hattest du Zeit?"},
    {"id":95,"software":[],"promptFa":"You had no time.","expectedAnswer":"Du hattest keine Zeit."},
    {"id":96,"software":[],"promptFa":"Why did you have no time?","expectedAnswer":"Warum hattest du keine Zeit?"},
    {"id":97,"software":[],"promptFa":"I had it.","expectedAnswer":"Ich hatte es."},
    {"id":98,"software":[],"promptFa":"I did not have it.","expectedAnswer":"Ich hatte es nicht."},
    {"id":99,"software":[],"promptFa":"I had not bought it.","expectedAnswer":"Ich hatte es nicht gekauft.","noteFa":"\"hatte + Partizip II\" can describe an action completed before another past event."},
    {"id":100,"software":[],"promptFa":"I had already bought it.","expectedAnswer":"Ich hatte es schon gekauft."},
    {"id":101,"software":[{"german":"warst","persian":"were, for \"du\""}],"promptFa":"You were there.","expectedAnswer":"Du warst da."},
    {"id":102,"software":[],"promptFa":"Where were you?","expectedAnswer":"Wo warst du?"},
    {"id":103,"software":[],"promptFa":"Where were you yesterday evening?","expectedAnswer":"Wo warst du gestern Abend?"},
    {"id":104,"software":[],"promptFa":"Were you there yesterday?","expectedAnswer":"Warst du gestern da?"},
    {"id":105,"software":[{"german":"wahr","persian":"true"}],"promptFa":"It is true.","expectedAnswer":"Es ist wahr."},
    {"id":106,"software":[],"promptFa":"It was true.","expectedAnswer":"Es war wahr."},
    {"id":107,"software":[{"german":"Wahrheit","persian":"truth"}],"promptFa":"It is the truth.","expectedAnswer":"Es ist die Wahrheit."},
    {"id":108,"software":[{"german":"wirklich","persian":"really / actually"}],"promptFa":"It is really true.","expectedAnswer":"Es ist wirklich wahr."},
    {"id":109,"software":[],"promptFa":"It was really true.","expectedAnswer":"Es war wirklich wahr."},
    {"id":110,"software":[],"promptFa":"Is that really true?","expectedAnswer":"Ist das wirklich wahr?"},
    {"id":111,"software":[],"promptFa":"It is really like that.","expectedAnswer":"Es ist wirklich so."},
    {"id":112,"software":[],"promptFa":"I really believe it.","expectedAnswer":"Ich glaube es wirklich."},
    {"id":113,"software":[{"german":"gesehen","persian":"seen"}],"promptFa":"I saw it.","expectedAnswer":"Ich habe es gesehen."},
    {"id":114,"software":[],"promptFa":"Have you seen it?","expectedAnswer":"Haben Sie es gesehen?"},
    {"id":115,"software":[],"promptFa":"Have you seen it?","expectedAnswer":"Hast du es gesehen?"},
    {"id":116,"software":[],"promptFa":"I had seen it.","expectedAnswer":"Ich hatte es gesehen."},
    {"id":117,"software":[],"promptFa":"I have not seen it yet.","expectedAnswer":"Ich habe es noch nicht gesehen."},
    {"id":118,"software":[{"german":"gewartet","persian":"waited"}],"promptFa":"I waited for you.","expectedAnswer":"Ich habe auf Sie gewartet."},
    {"id":119,"software":[],"promptFa":"He waited for me.","expectedAnswer":"Er hat auf mich gewartet."},
    {"id":120,"software":[],"promptFa":"How long did you wait?","expectedAnswer":"Wie lange haben Sie gewartet?"},
    {"id":121,"software":[],"promptFa":"How long did you wait for me?","expectedAnswer":"Wie lange hast du auf mich gewartet?"},
    {"id":122,"software":[{"german":"gesucht","persian":"searched / looked for"}],"promptFa":"I searched for it.","expectedAnswer":"Ich habe es gesucht."},
    {"id":123,"software":[],"promptFa":"I searched for it, but I could not find it.","expectedAnswer":"Ich habe es gesucht, aber ich konnte es nicht finden."},
    {"id":124,"software":[],"promptFa":"Have you searched for it?","expectedAnswer":"Haben Sie es gesucht?"},
    {"id":125,"software":[],"promptFa":"I searched for it yesterday.","expectedAnswer":"Ich habe es gestern gesucht."},
    {"id":126,"software":[],"promptFa":"I bought it yesterday.","expectedAnswer":"Ich habe es gestern gekauft."},
    {"id":127,"software":[],"promptFa":"I have not bought it yet.","expectedAnswer":"Ich habe es noch nicht gekauft."},
    {"id":128,"software":[],"promptFa":"Why have you not bought it yet?","expectedAnswer":"Warum hast du es noch nicht gekauft?"},
    {"id":129,"software":[],"promptFa":"I sold it because I did not need it.","expectedAnswer":"Ich habe es verkauft, weil ich es nicht brauchte."},
    {"id":130,"software":[],"promptFa":"He has not sold it yet.","expectedAnswer":"Er hat es noch nicht verkauft."},
    {"id":131,"software":[],"promptFa":"I repaired it and checked it.","expectedAnswer":"Ich habe es repariert und kontrolliert."},
    {"id":132,"software":[],"promptFa":"He organized it very well.","expectedAnswer":"Er hat es sehr gut organisiert."},
    {"id":133,"software":[],"promptFa":"Everything is very well organized.","expectedAnswer":"Alles ist sehr gut organisiert."},
    {"id":134,"software":[],"promptFa":"I saw it, but I did not buy it.","expectedAnswer":"Ich habe es gesehen, aber ich habe es nicht gekauft."},
    {"id":135,"software":[],"promptFa":"I searched for it, but I could not find it.","expectedAnswer":"Ich habe es gesucht, aber ich konnte es nicht finden."},
    {"id":136,"software":[],"promptFa":"I waited for you, but you did not come.","expectedAnswer":"Ich habe auf Sie gewartet, aber Sie sind nicht gekommen."},
    {"id":137,"software":[],"promptFa":"Did you tell him?","expectedAnswer":"Haben Sie es ihm gesagt?"},
    {"id":138,"software":[],"promptFa":"He told me that it was true.","expectedAnswer":"Er hat mir gesagt, dass es wahr war."},
    {"id":139,"software":[],"promptFa":"I really do not know whether it is true.","expectedAnswer":"Ich weiß wirklich nicht, ob es wahr ist."},
    {"id":140,"software":[],"promptFa":"Could you tell me whether it is true?","expectedAnswer":"Könnten Sie mir sagen, ob es wahr ist?"},
    {"id":141,"software":[],"promptFa":"Where were you yesterday evening?","expectedAnswer":"Wo warst du gestern Abend?"},
    {"id":142,"software":[],"promptFa":"Did you have time yesterday?","expectedAnswer":"Hattest du gestern Zeit?"},
    {"id":143,"software":[],"promptFa":"Did you buy it?","expectedAnswer":"Hast du es gekauft?"},
    {"id":144,"software":[],"promptFa":"Why did you sell it?","expectedAnswer":"Warum hast du es verkauft?"},
    {"id":145,"software":[],"promptFa":"Have you seen it?","expectedAnswer":"Hast du es gesehen?"},
    {"id":146,"software":[],"promptFa":"How long did you wait?","expectedAnswer":"Wie lange hast du gewartet?"},
  ],
};
