// Lesson 10 content for the active-recall LessonPlayer (client/src/components/LessonPlayer.js).
// Same pattern as lesson1.js/lektion2.js/.../lektion9.js - see main.js's
// INTERACTIVE_LESSONS map, which intercepts the "deutsch-almani-lektion-10"
// course card (a plain courses-table row, just for the level/title/grid-
// card metadata) and renders this instead of the plain page reader.
//
// English-prompt lesson (promptLang: 'en') - SAY/NOTE/WORD translations are
// all English, not Persian, despite the field names (promptFa/noteFa/
// w.persian) being legacy - see LessonPlayer.js's file comment.
//
// Like lektion9.js, this one mixes formal "Sie" and informal "du"/"ihr"
// register, so registerHotwords is left empty rather than pinned to "Sie".

export const lektion10 = {
  id: 'lektion10',
  courseId: 'deutsch-almani-lektion-10',
  title: "Lektion 10 – Perfekt, Reisen, Kommunikation und persönliche Angaben",
  backHref: '#/courses/A1',
  backLabel: '← Courses',
  storageKey: 'lesson-progress-lektion-10-v1',
  promptLang: 'en',
  steps: [
    {"id":1,"software":[{"german":"vorbereiten","persian":"to prepare"}],"promptFa":"I have to prepare it.","expectedAnswer":"Ich muss es vorbereiten."},
    {"id":2,"software":[],"promptFa":"I should prepare it today.","expectedAnswer":"Ich sollte es heute vorbereiten."},
    {"id":3,"software":[{"german":"bereit","persian":"ready"}],"promptFa":"I am ready.","expectedAnswer":"Ich bin bereit."},
    {"id":4,"software":[],"promptFa":"Are you ready?","expectedAnswer":"Sind Sie bereit?"},
    {"id":5,"software":[{"german":"gewollt","persian":"wanted, past participle of \"wollen\""}],"promptFa":"I wanted it.","expectedAnswer":"Ich habe es gewollt."},
    {"id":6,"software":[{"german":"niemand","persian":"nobody"}],"promptFa":"Nobody was there.","expectedAnswer":"Niemand war da."},
    {"id":7,"software":[],"promptFa":"Nobody knows it.","expectedAnswer":"Niemand weiß es."},
    {"id":8,"software":[{"german":"wer","persian":"who"}],"promptFa":"Who was there?","expectedAnswer":"Wer war da?"},
    {"id":9,"software":[],"promptFa":"Who was there with you yesterday evening?","expectedAnswer":"Wer war gestern Abend mit Ihnen da?"},
    {"id":10,"software":[{"german":"in","persian":"in"},{"german":"Ruhe","persian":"peace / quiet"}],"promptFa":"Leave me in peace.","expectedAnswer":"Lassen Sie mich in Ruhe."},
    {"id":11,"software":[{"german":"lass","persian":"let, informal command form"}],"promptFa":"Leave me in peace.","expectedAnswer":"Lass mich in Ruhe."},
    {"id":12,"software":[{"german":"dunkel","persian":"dark"}],"promptFa":"It is dark.","expectedAnswer":"Es ist dunkel."},
    {"id":13,"software":[],"promptFa":"It is very dark.","expectedAnswer":"Es ist sehr dunkel."},
    {"id":14,"software":[{"german":"Dunkelheit","persian":"darkness"}],"promptFa":"The darkness is here.","expectedAnswer":"Die Dunkelheit ist hier."},
    {"id":15,"software":[{"german":"wurde","persian":"became / got, past of \"werden\""}],"promptFa":"It became dark.","expectedAnswer":"Es wurde dunkel."},
    {"id":16,"software":[{"german":"plötzlich","persian":"suddenly"}],"promptFa":"It suddenly became dark.","expectedAnswer":"Es wurde plötzlich dunkel."},
    {"id":17,"software":[{"german":"wurden","persian":"became, plural past of \"werden\""}],"promptFa":"We became tired.","expectedAnswer":"Wir wurden müde."},
    {"id":18,"software":[],"promptFa":"We suddenly became tired.","expectedAnswer":"Wir wurden plötzlich müde."},
    {"id":19,"software":[{"german":"wusste","persian":"knew, past of \"wissen\""}],"promptFa":"I knew it.","expectedAnswer":"Ich wusste es."},
    {"id":20,"software":[],"promptFa":"I did not know it.","expectedAnswer":"Ich wusste es nicht."},
    {"id":21,"software":[{"german":"gewusst","persian":"known"}],"promptFa":"I knew it.","expectedAnswer":"Ich habe es gewusst."},
    {"id":22,"software":[{"german":"gegangen","persian":"gone / went"}],"promptFa":"I went.","expectedAnswer":"Ich bin gegangen.","noteFa":"Movement verbs such as \"gehen\" normally form the Perfekt with \"sein\"."},
    {"id":23,"software":[],"promptFa":"We went.","expectedAnswer":"Wir sind gegangen."},
    {"id":24,"software":[],"promptFa":"I went there.","expectedAnswer":"Ich bin dorthin gegangen."},
    {"id":25,"software":[],"promptFa":"We went there yesterday evening.","expectedAnswer":"Wir sind gestern Abend dorthin gegangen."},
    {"id":26,"software":[],"promptFa":"When did you go there?","expectedAnswer":"Wann sind Sie dorthin gegangen?"},
    {"id":27,"software":[{"german":"gewesen","persian":"been"}],"promptFa":"I was there.","expectedAnswer":"Ich bin dort gewesen."},
    {"id":28,"software":[],"promptFa":"We were there yesterday evening.","expectedAnswer":"Wir sind gestern Abend dort gewesen."},
    {"id":29,"software":[],"promptFa":"How long were you there?","expectedAnswer":"Wie lange sind Sie dort gewesen?"},
    {"id":30,"software":[{"german":"gehabt","persian":"had"}],"promptFa":"I had it.","expectedAnswer":"Ich habe es gehabt."},
    {"id":31,"software":[],"promptFa":"I had already had it.","expectedAnswer":"Ich hatte es schon gehabt."},
    {"id":32,"software":[{"german":"dich","persian":"you, informal accusative"}],"promptFa":"I waited for you.","expectedAnswer":"Ich habe auf dich gewartet."},
    {"id":33,"software":[],"promptFa":"I saw you yesterday.","expectedAnswer":"Ich habe dich gestern gesehen."},
    {"id":34,"software":[{"german":"angekommen","persian":"arrived"}],"promptFa":"He arrived today.","expectedAnswer":"Er ist heute angekommen."},
    {"id":35,"software":[],"promptFa":"When did you arrive?","expectedAnswer":"Wann sind Sie angekommen?"},
    {"id":36,"software":[],"promptFa":"I arrived yesterday evening.","expectedAnswer":"Ich bin gestern Abend angekommen."},
    {"id":37,"software":[{"german":"geblieben","persian":"stayed"}],"promptFa":"We stayed.","expectedAnswer":"Wir sind geblieben."},
    {"id":38,"software":[],"promptFa":"We stayed there.","expectedAnswer":"Wir sind dort geblieben."},
    {"id":39,"software":[],"promptFa":"How long did you stay there?","expectedAnswer":"Wie lange sind Sie dort geblieben?"},
    {"id":40,"software":[{"german":"gefahren","persian":"traveled / driven"}],"promptFa":"I traveled to Berlin.","expectedAnswer":"Ich bin nach Berlin gefahren."},
    {"id":41,"software":[{"german":"Wien","persian":"Vienna"}],"promptFa":"We traveled to Vienna.","expectedAnswer":"Wir sind nach Wien gefahren."},
    {"id":42,"software":[],"promptFa":"When did you travel to Vienna?","expectedAnswer":"Wann sind Sie nach Wien gefahren?"},
    {"id":43,"software":[{"german":"letzte","persian":"last"},{"german":"Woche","persian":"week"}],"promptFa":"We traveled to Vienna last week.","expectedAnswer":"Wir sind letzte Woche nach Wien gefahren."},
    {"id":44,"software":[{"german":"nur","persian":"only"},{"german":"paar","persian":"few"},{"german":"Tage","persian":"days"}],"promptFa":"We stayed only a few days.","expectedAnswer":"Wir sind nur ein paar Tage geblieben."},
    {"id":45,"software":[{"german":"London","persian":"London"},{"german":"zurückgekommen","persian":"returned / came back"}],"promptFa":"We returned to London.","expectedAnswer":"Wir sind nach London zurückgekommen."},
    {"id":46,"software":[],"promptFa":"We traveled to Vienna last week, stayed only a few days, and returned to London.","expectedAnswer":"Wir sind letzte Woche nach Wien gefahren, wir sind nur ein paar Tage geblieben und wir sind nach London zurückgekommen."},
    {"id":47,"software":[{"german":"beeilt","persian":"hurried"}],"promptFa":"I hurried.","expectedAnswer":"Ich habe mich beeilt."},
    {"id":48,"software":[],"promptFa":"We hurried.","expectedAnswer":"Wir haben uns beeilt."},
    {"id":49,"software":[{"german":"aufstehen","persian":"to get up"}],"promptFa":"I have to get up.","expectedAnswer":"Ich muss aufstehen."},
    {"id":50,"software":[{"german":"aufgestanden","persian":"got up"}],"promptFa":"I got up.","expectedAnswer":"Ich bin aufgestanden."},
    {"id":51,"software":[],"promptFa":"We got up.","expectedAnswer":"Wir sind aufgestanden."},
    {"id":52,"software":[],"promptFa":"At what time did you get up?","expectedAnswer":"Um wie viel Uhr sind Sie aufgestanden?"},
    {"id":53,"software":[{"german":"ruhig","persian":"quiet / calm"}],"promptFa":"It is very quiet here.","expectedAnswer":"Es ist hier sehr ruhig."},
    {"id":54,"software":[{"german":"ausruhen","persian":"to rest"}],"promptFa":"I will rest.","expectedAnswer":"Ich werde mich ausruhen."},
    {"id":55,"software":[],"promptFa":"You should rest.","expectedAnswer":"Sie sollten sich ausruhen."},
    {"id":56,"software":[{"german":"ausgeruht","persian":"rested"}],"promptFa":"I rested very well.","expectedAnswer":"Ich habe mich sehr gut ausgeruht."},
    {"id":57,"software":[{"german":"manchmal","persian":"sometimes"}],"promptFa":"Sometimes one has to rest.","expectedAnswer":"Manchmal muss man sich ausruhen."},
    {"id":58,"software":[],"promptFa":"Sometimes I cannot understand it.","expectedAnswer":"Manchmal kann ich es nicht verstehen."},
    {"id":59,"software":[{"german":"schlafen","persian":"to sleep"}],"promptFa":"I want to sleep.","expectedAnswer":"Ich will schlafen."},
    {"id":60,"software":[{"german":"geschlafen","persian":"slept"}],"promptFa":"I slept very well.","expectedAnswer":"Ich habe sehr gut geschlafen."},
    {"id":61,"software":[],"promptFa":"Did you sleep well?","expectedAnswer":"Haben Sie gut geschlafen?"},
    {"id":62,"software":[{"german":"verstanden","persian":"understood"}],"promptFa":"I did not understand it.","expectedAnswer":"Ich habe es nicht verstanden."},
    {"id":63,"software":[],"promptFa":"I did not understand what you said.","expectedAnswer":"Ich habe nicht verstanden, was Sie gesagt haben."},
    {"id":64,"software":[{"german":"meinen","persian":"to mean / think"}],"promptFa":"What do you mean?","expectedAnswer":"Was meinen Sie?"},
    {"id":65,"software":[],"promptFa":"I do not understand what you mean.","expectedAnswer":"Ich verstehe nicht, was Sie meinen."},
    {"id":66,"software":[{"german":"meint","persian":"means / thinks"}],"promptFa":"What does he mean?","expectedAnswer":"Was meint er?"},
    {"id":67,"software":[{"german":"senden","persian":"to send"}],"promptFa":"I will send it to you.","expectedAnswer":"Ich werde es Ihnen senden."},
    {"id":68,"software":[{"german":"schicken","persian":"to send"}],"promptFa":"I will send it to you.","expectedAnswer":"Ich werde es Ihnen schicken."},
    {"id":69,"software":[{"german":"geschickt","persian":"sent"}],"promptFa":"He sent it to me.","expectedAnswer":"Er hat es mir geschickt."},
    {"id":70,"software":[],"promptFa":"Did you send it to me?","expectedAnswer":"Haben Sie es mir geschickt?"},
    {"id":71,"software":[{"german":"erhalten","persian":"to receive"}],"promptFa":"I have not received it yet.","expectedAnswer":"Ich habe es noch nicht erhalten."},
    {"id":72,"software":[{"german":"behalten","persian":"to keep"}],"promptFa":"You can keep it.","expectedAnswer":"Sie können es behalten."},
    {"id":73,"software":[],"promptFa":"I would like to keep it.","expectedAnswer":"Ich möchte es behalten."},
    {"id":74,"software":[{"german":"hören","persian":"to hear"}],"promptFa":"I cannot hear it.","expectedAnswer":"Ich kann es nicht hören."},
    {"id":75,"software":[],"promptFa":"Can you hear me?","expectedAnswer":"Können Sie mich hören?"},
    {"id":76,"software":[{"german":"gehören","persian":"to belong to"}],"promptFa":"It belongs to me.","expectedAnswer":"Es gehört mir."},
    {"id":77,"software":[{"german":"gehört","persian":"belongs / belonged"}],"promptFa":"It does not belong to me.","expectedAnswer":"Es gehört mir nicht."},
    {"id":78,"software":[],"promptFa":"Does it belong to you?","expectedAnswer":"Gehört es Ihnen?"},
    {"id":79,"software":[{"german":"antworten","persian":"to answer"}],"promptFa":"Please answer.","expectedAnswer":"Antworten Sie bitte."},
    {"id":80,"software":[{"german":"Wort","persian":"word"}],"promptFa":"I do not understand the word.","expectedAnswer":"Ich verstehe das Wort nicht."},
    {"id":81,"software":[{"german":"Antwort","persian":"answer"}],"promptFa":"I know the answer.","expectedAnswer":"Ich weiß die Antwort."},
    {"id":82,"software":[{"german":"geantwortet","persian":"answered"}],"promptFa":"He has not answered yet.","expectedAnswer":"Er hat noch nicht geantwortet."},
    {"id":83,"software":[],"promptFa":"Why has he not answered yet?","expectedAnswer":"Warum hat er noch nicht geantwortet?"},
    {"id":84,"software":[{"german":"gerufen","persian":"called / shouted"}],"promptFa":"He called.","expectedAnswer":"Er hat gerufen."},
    {"id":85,"software":[{"german":"angerufen","persian":"called by phone"}],"promptFa":"He called me.","expectedAnswer":"Er hat mich angerufen."},
    {"id":86,"software":[],"promptFa":"I called you this morning.","expectedAnswer":"Ich habe Sie heute früh angerufen."},
    {"id":87,"software":[{"german":"bei","persian":"at / with / at someone's place"}],"promptFa":"I will be at your place at ten o'clock.","expectedAnswer":"Ich werde um zehn Uhr bei Ihnen sein."},
    {"id":88,"software":[],"promptFa":"I called you this morning to tell you that I will arrive this evening.","expectedAnswer":"Ich habe Sie heute früh angerufen, um Ihnen zu sagen, dass ich heute Abend ankommen werde."},
    {"id":89,"software":[{"german":"erinnern","persian":"to remember"}],"promptFa":"I cannot remember.","expectedAnswer":"Ich kann mich nicht erinnern."},
    {"id":90,"software":[{"german":"erinnere","persian":"I remember"}],"promptFa":"I remember.","expectedAnswer":"Ich erinnere mich."},
    {"id":91,"software":[{"german":"Kindheit","persian":"childhood"}],"promptFa":"I remember my childhood.","expectedAnswer":"Ich erinnere mich an meine Kindheit."},
    {"id":92,"software":[],"promptFa":"I do not remember my childhood.","expectedAnswer":"Ich erinnere mich nicht an meine Kindheit."},
    {"id":93,"software":[{"german":"Wohnung","persian":"apartment"}],"promptFa":"I would like an apartment.","expectedAnswer":"Ich möchte eine Wohnung."},
    {"id":94,"software":[{"german":"mieten","persian":"to rent"}],"promptFa":"I will rent the apartment.","expectedAnswer":"Ich werde die Wohnung mieten."},
    {"id":95,"software":[],"promptFa":"I would like to rent an apartment.","expectedAnswer":"Ich möchte eine Wohnung mieten."},
    {"id":96,"software":[{"german":"zum","persian":"to the / for the"},{"german":"Beispiel","persian":"example"}],"promptFa":"For example.","expectedAnswer":"Zum Beispiel."},
    {"id":97,"software":[{"german":"spielen","persian":"to play"}],"promptFa":"I like to play.","expectedAnswer":"Ich spiele gern."},
    {"id":98,"software":[{"german":"Klavier","persian":"piano"}],"promptFa":"I play the piano.","expectedAnswer":"Ich spiele Klavier."},
    {"id":99,"software":[],"promptFa":"For example, I play the piano.","expectedAnswer":"Zum Beispiel spiele ich Klavier."},
    {"id":100,"software":[{"german":"Ihr","persian":"your, formal / your, plural informal depending on capitalization"},{"german":"ihr","persian":"you, informal plural / her"}],"promptFa":"You all are here.","expectedAnswer":"Ihr seid hier.","noteFa":"Here \"ihr\" is introduced as the informal plural \"you\"."},
    {"id":101,"software":[{"german":"könnt","persian":"can, informal plural"}],"promptFa":"You all can come with me.","expectedAnswer":"Ihr könnt mit mir kommen."},
    {"id":102,"software":[{"german":"helfen","persian":"to help"}],"promptFa":"Can you all help me?","expectedAnswer":"Könnt ihr mir helfen?"},
    {"id":103,"software":[{"german":"euch","persian":"you, informal plural object"}],"promptFa":"I want to help you all.","expectedAnswer":"Ich will euch helfen."},
    {"id":104,"software":[{"german":"wollt","persian":"want, informal plural"}],"promptFa":"Do you all want to come with me?","expectedAnswer":"Wollt ihr mit mir kommen?"},
    {"id":105,"software":[{"german":"müsst","persian":"must / have to, informal plural"},{"german":"am","persian":"at the / in the"}],"promptFa":"If you all want to come with me, you have to be here in the evening.","expectedAnswer":"Wenn ihr mit mir kommen wollt, müsst ihr am Abend hier sein."},
    {"id":106,"software":[{"german":"ihn","persian":"him, accusative"}],"promptFa":"I have to call him.","expectedAnswer":"Ich muss ihn anrufen."},
    {"id":107,"software":[{"german":"gekommen","persian":"come"}],"promptFa":"He came here.","expectedAnswer":"Er ist hierher gekommen."},
    {"id":108,"software":[{"german":"treffen","persian":"to meet"}],"promptFa":"I could not meet him.","expectedAnswer":"Ich konnte ihn nicht treffen."},
    {"id":109,"software":[],"promptFa":"He came here, but I could not meet him.","expectedAnswer":"Er ist hierher gekommen, aber ich konnte ihn nicht treffen."},
    {"id":110,"software":[{"german":"ihm","persian":"to him"}],"promptFa":"I told him.","expectedAnswer":"Ich habe es ihm gesagt."},
    {"id":111,"software":[],"promptFa":"I had to tell him that I had no time.","expectedAnswer":"Ich musste ihm sagen, dass ich keine Zeit hatte."},
    {"id":112,"software":[{"german":"geholfen","persian":"helped"}],"promptFa":"Why did you not help him?","expectedAnswer":"Warum hast du ihm nicht geholfen?"},
    {"id":113,"software":[],"promptFa":"Why did you not help her?","expectedAnswer":"Warum hast du ihr nicht geholfen?"},
    {"id":114,"software":[{"german":"auswandern","persian":"to emigrate"}],"promptFa":"I want to emigrate.","expectedAnswer":"Ich will auswandern."},
    {"id":115,"software":[{"german":"wandere","persian":"I migrate / emigrate"},{"german":"dieses","persian":"this"},{"german":"Jahr","persian":"year"}],"promptFa":"I am emigrating this year.","expectedAnswer":"Ich wandere dieses Jahr aus."},
    {"id":116,"software":[{"german":"Auswanderung","persian":"emigration"},{"german":"gute","persian":"good, inflected form"}],"promptFa":"Emigration can be a good opportunity.","expectedAnswer":"Die Auswanderung kann eine gute Gelegenheit sein."},
    {"id":117,"software":[],"promptFa":"Everyone knows that emigration can be a good opportunity.","expectedAnswer":"Alle wissen, dass die Auswanderung eine gute Gelegenheit sein kann."},
    {"id":118,"software":[{"german":"heißen","persian":"to be called"}],"promptFa":"What are you called?","expectedAnswer":"Wie heißen Sie?"},
    {"id":119,"software":[{"german":"heißt","persian":"is called"}],"promptFa":"What is he called?","expectedAnswer":"Wie heißt er?"},
    {"id":120,"software":[{"german":"heiße","persian":"am called"}],"promptFa":"My name is Anna.","expectedAnswer":"Ich heiße Anna."},
    {"id":121,"software":[{"german":"wohnst","persian":"live, for \"du\""}],"promptFa":"Where do you live?","expectedAnswer":"Wo wohnst du?"},
    {"id":122,"software":[{"german":"woher","persian":"where from"}],"promptFa":"Where are you from?","expectedAnswer":"Woher kommen Sie?"},
    {"id":123,"software":[{"german":"Iran","persian":"Iran"}],"promptFa":"I come from Iran.","expectedAnswer":"Ich komme aus dem Iran."},
    {"id":124,"software":[{"german":"alt","persian":"old"},{"german":"bist","persian":"are, for \"du\""}],"promptFa":"How old are you?","expectedAnswer":"Wie alt bist du?"},
    {"id":125,"software":[{"german":"Jahre","persian":"years"}],"promptFa":"I am thirty years old.","expectedAnswer":"Ich bin dreißig Jahre alt."},
    {"id":126,"software":[{"german":"von","persian":"of / from"},{"german":"Beruf","persian":"profession"}],"promptFa":"What is your profession?","expectedAnswer":"Was sind Sie von Beruf?"},
    {"id":127,"software":[],"promptFa":"What is your profession?","expectedAnswer":"Was bist du von Beruf?"},
    {"id":128,"software":[{"german":"Krankenschwester","persian":"nurse"}],"promptFa":"I am a nurse.","expectedAnswer":"Ich bin Krankenschwester von Beruf."},
    {"id":129,"software":[{"german":"Sprache","persian":"language"}],"promptFa":"German is a language.","expectedAnswer":"Deutsch ist eine Sprache."},
    {"id":130,"software":[{"german":"Muttersprache","persian":"native language / mother tongue"}],"promptFa":"German is not my native language.","expectedAnswer":"Deutsch ist nicht meine Muttersprache."},
    {"id":131,"software":[{"german":"welche","persian":"which"},{"german":"Sprachen","persian":"languages"}],"promptFa":"Which languages do you speak?","expectedAnswer":"Welche Sprachen sprechen Sie?"},
    {"id":132,"software":[{"german":"spreche","persian":"I speak"},{"german":"Persisch","persian":"Persian"}],"promptFa":"I speak Persian.","expectedAnswer":"Ich spreche Persisch."},
    {"id":133,"software":[],"promptFa":"My native language is Persian.","expectedAnswer":"Meine Muttersprache ist Persisch."},
    {"id":134,"software":[{"german":"abschließen","persian":"to complete / graduate from"}],"promptFa":"I want to complete my studies.","expectedAnswer":"Ich möchte mein Studium abschließen."},
    {"id":135,"software":[{"german":"Studium","persian":"studies / university studies"}],"promptFa":"Where did you complete your studies?","expectedAnswer":"Wo haben Sie Ihr Studium abgeschlossen?"},
    {"id":136,"software":[{"german":"abgeschlossen","persian":"completed / graduated"}],"promptFa":"I completed my studies.","expectedAnswer":"Ich habe mein Studium abgeschlossen."},
    {"id":137,"software":[{"german":"Tehran","persian":"Tehran"},{"german":"Universität","persian":"university"}],"promptFa":"I completed my studies at the University of Tehran.","expectedAnswer":"Ich habe mein Studium an der Universität Tehran abgeschlossen."},
    {"id":138,"software":[{"german":"lernen","persian":"to learn"}],"promptFa":"I have to learn German.","expectedAnswer":"Ich muss Deutsch lernen."},
    {"id":139,"software":[{"german":"auszuwandern","persian":"to emigrate, \"zu\" infinitive form"}],"promptFa":"I have to learn German in order to emigrate to Germany.","expectedAnswer":"Ich muss Deutsch lernen, um nach Deutschland auszuwandern."},
    {"id":140,"software":[],"promptFa":"In order to emigrate to Germany, I have to learn German.","expectedAnswer":"Um nach Deutschland auszuwandern, muss ich Deutsch lernen."},
    {"id":141,"software":[{"german":"angefangen","persian":"started"}],"promptFa":"I started learning German.","expectedAnswer":"Ich habe angefangen, Deutsch zu lernen."},
    {"id":142,"software":[{"german":"sicher","persian":"sure / certain"}],"promptFa":"I am sure.","expectedAnswer":"Ich bin sicher."},
    {"id":143,"software":[{"german":"schnell","persian":"quickly / fast"},{"german":"diese","persian":"this"}],"promptFa":"I am sure that I will learn this language very quickly.","expectedAnswer":"Ich bin sicher, dass ich diese Sprache sehr schnell lernen werde."},
    {"id":144,"software":[{"german":"einfach","persian":"easy / simple"}],"promptFa":"German is easy.","expectedAnswer":"Deutsch ist einfach."},
    {"id":145,"software":[],"promptFa":"Now I can say that German is easy.","expectedAnswer":"Jetzt kann ich sagen, dass Deutsch einfach ist."},
    {"id":146,"software":[{"german":"fließend","persian":"fluently"}],"promptFa":"I would like to speak German fluently.","expectedAnswer":"Ich möchte Deutsch fließend sprechen."},
    {"id":147,"software":[],"promptFa":"I am sure that I will speak this language fluently.","expectedAnswer":"Ich bin sicher, dass ich diese Sprache fließend sprechen werde."},
    {"id":148,"software":[],"promptFa":"I went to Vienna last week.","expectedAnswer":"Ich bin letzte Woche nach Wien gefahren."},
    {"id":149,"software":[],"promptFa":"I stayed there only a few days.","expectedAnswer":"Ich bin dort nur ein paar Tage geblieben."},
    {"id":150,"software":[],"promptFa":"Then I returned to London.","expectedAnswer":"Dann bin ich nach London zurückgekommen."},
    {"id":151,"software":[],"promptFa":"I got up early, but I was still tired.","expectedAnswer":"Ich bin früh aufgestanden, aber ich war noch müde."},
    {"id":152,"software":[],"promptFa":"I rested and slept very well.","expectedAnswer":"Ich habe mich ausgeruht und sehr gut geschlafen."},
    {"id":153,"software":[],"promptFa":"I did not understand what you meant.","expectedAnswer":"Ich habe nicht verstanden, was Sie gemeint haben."},
    {"id":154,"software":[],"promptFa":"He sent it to me, but I have not received it yet.","expectedAnswer":"Er hat es mir geschickt, aber ich habe es noch nicht erhalten."},
    {"id":155,"software":[],"promptFa":"Can you hear me?","expectedAnswer":"Können Sie mich hören?"},
    {"id":156,"software":[],"promptFa":"It belongs to me.","expectedAnswer":"Es gehört mir."},
    {"id":157,"software":[],"promptFa":"He has not answered yet.","expectedAnswer":"Er hat noch nicht geantwortet."},
    {"id":158,"software":[],"promptFa":"I called you this morning, but nobody answered.","expectedAnswer":"Ich habe Sie heute früh angerufen, aber niemand hat geantwortet."},
    {"id":159,"software":[],"promptFa":"I cannot remember my childhood very well.","expectedAnswer":"Ich kann mich nicht sehr gut an meine Kindheit erinnern."},
    {"id":160,"software":[],"promptFa":"I would like to rent an apartment.","expectedAnswer":"Ich möchte eine Wohnung mieten."},
    {"id":161,"software":[],"promptFa":"For example, I like to play the piano.","expectedAnswer":"Zum Beispiel spiele ich gern Klavier."},
    {"id":162,"software":[],"promptFa":"Can you all help me?","expectedAnswer":"Könnt ihr mir helfen?"},
    {"id":163,"software":[],"promptFa":"I called him yesterday, but I could not meet him.","expectedAnswer":"Ich habe ihn gestern angerufen, aber ich konnte ihn nicht treffen."},
    {"id":164,"software":[],"promptFa":"I want to emigrate to Germany.","expectedAnswer":"Ich will nach Deutschland auswandern."},
    {"id":165,"software":[],"promptFa":"Where are you from?","expectedAnswer":"Woher kommen Sie?"},
    {"id":166,"software":[],"promptFa":"What is your profession?","expectedAnswer":"Was sind Sie von Beruf?"},
    {"id":167,"software":[],"promptFa":"Which languages do you speak?","expectedAnswer":"Welche Sprachen sprechen Sie?"},
    {"id":168,"software":[],"promptFa":"My native language is Persian.","expectedAnswer":"Meine Muttersprache ist Persisch."},
    {"id":169,"software":[],"promptFa":"Where did you complete your studies?","expectedAnswer":"Wo haben Sie Ihr Studium abgeschlossen?"},
    {"id":170,"software":[],"promptFa":"I started learning German.","expectedAnswer":"Ich habe angefangen, Deutsch zu lernen."},
    {"id":171,"software":[],"promptFa":"I am sure that I will learn German quickly.","expectedAnswer":"Ich bin sicher, dass ich Deutsch schnell lernen werde."},
    {"id":172,"software":[],"promptFa":"I am sure that I will speak German fluently.","expectedAnswer":"Ich bin sicher, dass ich Deutsch fließend sprechen werde."},
  ],
};
